import type { ResolvedBuildPlan } from "@/server/build-planner";
import { resolveBuildProvider } from "@/server/build-planner";
import { normalizeBuildEnvInput } from "@/server/projects/project-build-env";
import { JenkinsBuildBackend } from "@/server/build-backend-jenkins";
import { TektonBuildBackend } from "@/server/build-backend-tekton";
export interface BuildProjectRecord {
    id: string;
    projectName: string;
    gitRepositoryUrl: string;
    branch: string;
    gitCredentialsId?: string | null;
    language: string;
    autoGenerateDockerfile: boolean;
    autoGenerateHelmChart: boolean;
    namespace: string;
    buildEnv?: Record<string, string> | null;
}
export function toBuildProjectRecord(project: {
    id: string;
    projectName: string;
    gitRepositoryUrl: string;
    branch: string;
    gitCredentialsId?: string | null;
    language: string;
    autoGenerateDockerfile: boolean;
    autoGenerateHelmChart: boolean;
    namespace: string;
    buildEnv?: unknown;
}): BuildProjectRecord {
    return {
        id: project.id,
        projectName: project.projectName,
        gitRepositoryUrl: project.gitRepositoryUrl,
        branch: project.branch,
        gitCredentialsId: project.gitCredentialsId,
        language: project.language,
        autoGenerateDockerfile: project.autoGenerateDockerfile,
        autoGenerateHelmChart: project.autoGenerateHelmChart,
        namespace: project.namespace,
        buildEnv: normalizeBuildEnvInput(project.buildEnv)
    };
}
export interface BuildTriggerResult {
    accepted: boolean;
    provider: "jenkins" | "tekton";
    runId: string | null;
    runNumber: number | null;
    logs: string;
    externalUrl?: string | null;
    artifactImage?: string | null;
    artifactDigest?: string | null;
}
export interface BuildDeploymentBaseline {
    runNumber: number | null;
}
export interface MonitorDeploymentArgs {
    deploymentId: string;
    project: BuildProjectRecord;
    plan: ResolvedBuildPlan;
    startedRun: BuildTriggerResult;
    baseline: BuildDeploymentBaseline;
}
export interface BuildTriggerOptions {
    branchOverride?: string;
    gitCredentialsIdOverride?: string | null;
}
export interface BuildBackend {
    readonly provider: "jenkins" | "tekton";
    provisionProjectIntegration(project: BuildProjectRecord, plan: ResolvedBuildPlan): Promise<void>;
    triggerBuild(project: BuildProjectRecord, plan: ResolvedBuildPlan, options?: BuildTriggerOptions): Promise<BuildTriggerResult>;
    getDeploymentBaseline(project: BuildProjectRecord): Promise<BuildDeploymentBaseline>;
    triggerDeployment(project: BuildProjectRecord, plan: ResolvedBuildPlan, options?: BuildTriggerOptions): Promise<BuildTriggerResult>;
    monitorDeployment(args: MonitorDeploymentArgs): Promise<void>;
}
let backend: BuildBackend | null = null;
export function getBuildBackend(): BuildBackend {
    if (backend) {
        return backend;
    }
    backend = resolveBuildProvider() === "tekton" ? new TektonBuildBackend() : new JenkinsBuildBackend();
    return backend;
}
