apiVersion: v1
kind: Secret
metadata:
  name: paas-secrets
  namespace: devsecops-paas
type: Opaque
stringData:
  DATABASE_URL: postgresql://paas:paas@postgres:5432/paas
  JWT_SECRET: change-this-secret
  JWT_EXPIRES_IN: 2h
  JENKINS_API_TOKEN: token
  SONAR_TOKEN: token
  DEPENDENCY_TRACK_API_KEY: token
  TRIVY_AUTH_TOKEN: token
  ARGOCD_AUTH_TOKEN: token
  GITOPS_REPO_TOKEN: token
