apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: paas-secrets
  namespace: devsecops-paas
spec:
  encryptedData:
    DATABASE_URL: AgReplaceWithClusterSpecificCiphertext
    JWT_SECRET: AgReplaceWithClusterSpecificCiphertext
    JWT_EXPIRES_IN: AgReplaceWithClusterSpecificCiphertext
    JENKINS_API_TOKEN: AgReplaceWithClusterSpecificCiphertext
    SONAR_TOKEN: AgReplaceWithClusterSpecificCiphertext
    DEPENDENCY_TRACK_API_KEY: AgReplaceWithClusterSpecificCiphertext
    TRIVY_AUTH_TOKEN: AgReplaceWithClusterSpecificCiphertext
    ARGOCD_AUTH_TOKEN: AgReplaceWithClusterSpecificCiphertext
    GITOPS_REPO_TOKEN: AgReplaceWithClusterSpecificCiphertext
  template:
    metadata:
      name: paas-secrets
      namespace: devsecops-paas
    type: Opaque
