import * as jwt from "jsonwebtoken";
import { test, expect } from "@playwright/test";
const JWT_SECRET = "playwright-test-secret-min-32-chars!!";
const PROJECT_ID = "e2e-playwright-project";
const DEPLOYMENT_ID = "e2e-deployment-1";
test.describe("Deploy UI (API mocked in browser)", () => {
    test.beforeEach(async ({ page }) => {
        const token = jwt.sign({ userId: "u1", email: "e2e@test.com", role: "ADMIN" }, JWT_SECRET, { expiresIn: "2h" });
        const userJson = JSON.stringify({
            id: "u1",
            email: "e2e@test.com",
            fullName: "E2E User",
            role: "ADMIN"
        });
        await page.addInitScript(([tok, u]) => {
            localStorage.setItem("paas_token", tok);
            localStorage.setItem("paas_user", u);
        }, [token, userJson] as [
            string,
            string
        ]);
        await page.route("**/api/**", async (route) => {
            const req = route.request();
            const url = req.url();
            const method = req.method();
            if (method === "GET" && url.includes(`/api/project/${PROJECT_ID}`)) {
                await route.fulfill({
                    status: 200,
                    contentType: "application/json",
                    body: JSON.stringify({
                        id: PROJECT_ID,
                        projectName: "e2e-playwright",
                        gitRepositoryUrl: "https://github.com/o/r.git",
                        branch: "main",
                        language: "node",
                        buildProvider: "tekton",
                        buildProfile: "node",
                        buildMode: "platform-template",
                        buildTemplateName: "node-service",
                        buildTemplateVersion: "v1",
                        buildDetectionReason: "Detected from stack \"node\".",
                        namespace: "e2e-playwright",
                        imageTag: "",
                        buildStatus: "SUCCESS",
                        lastDeploymentStatus: "NOT_DEPLOYED",
                        podStatus: "Running",
                        createdAt: new Date().toISOString(),
                        autoGenerateDockerfile: false,
                        autoGenerateHelmChart: false,
                        url: ""
                    })
                });
                return;
            }
            if (method === "GET" && url.includes(`/api/status/${PROJECT_ID}`)) {
                await route.fulfill({
                    status: 200,
                    contentType: "application/json",
                    body: JSON.stringify({
                        projectId: PROJECT_ID,
                        namespace: "e2e-playwright",
                        imageTag: "",
                        podStatus: "Running",
                        buildLogs: "",
                        deploymentLogs: "",
                        buildProvider: "tekton",
                        buildProfile: "node",
                        buildMode: "platform-template",
                        lastDeploymentStatus: "NOT_DEPLOYED"
                    })
                });
                return;
            }
            if (method === "GET" && url.includes(`/api/argocd/${PROJECT_ID}`)) {
                await route.fulfill({
                    status: 200,
                    contentType: "application/json",
                    body: JSON.stringify({
                        health: "Healthy",
                        syncStatus: "Synced",
                        appName: "paas-e2e-playwright"
                    })
                });
                return;
            }
            if (method === "GET" && url.includes(`/api/projects/${PROJECT_ID}/deployments`)) {
                await route.fulfill({
                    status: 200,
                    contentType: "application/json",
                    body: JSON.stringify([])
                });
                return;
            }
            if (method === "POST" && url.includes(`/api/deploy/${PROJECT_ID}`)) {
                await route.fulfill({
                    status: 200,
                    contentType: "application/json",
                    body: JSON.stringify({
                        status: "SUCCESS",
                        message: "Deployment queued (E2E mock)",
                        deploymentId: DEPLOYMENT_ID,
                        buildProvider: "tekton",
                        buildRunId: "tekton-run-1",
                        deploymentLogUrl: ""
                    })
                });
                return;
            }
            if (method === "GET" && url.includes(`/api/deployments/${DEPLOYMENT_ID}`)) {
                await route.fulfill({
                    status: 200,
                    contentType: "application/json",
                    body: JSON.stringify({
                        id: DEPLOYMENT_ID,
                        projectId: PROJECT_ID,
                        status: "PENDING",
                        logs: "E2E mock console: pipeline starting…",
                        buildNumber: null,
                        buildProvider: "tekton",
                        buildRunId: "tekton-run-1",
                        artifactImage: "harbor.test/paas/e2e-playwright:tekton-run-1",
                        artifactDigest: "sha256:abc123",
                        url: null,
                        failureReason: null,
                        failureMessage: null
                    })
                });
                return;
            }
            await route.continue();
        });
    });
    test("Deploy click then deployment page shows status and logs", async ({ page }) => {
        await page.goto(`/projects/${PROJECT_ID}`);
        await expect(page.getByRole("button", { name: "Deploy", exact: true })).toBeVisible();
        await page.getByRole("button", { name: "Deploy", exact: true }).click();
        await page.goto(`/deployments/${DEPLOYMENT_ID}`);
        await expect(page.getByText("PENDING")).toBeVisible();
        await expect(page.getByText(/E2E mock console/i)).toBeVisible();
        await expect(page.getByText("tekton", { exact: true })).toBeVisible();
    });
});
