import axios from "axios";
export interface JenkinsPipelineTrigger {
    projectId: string;
    branch: string;
    gitRepoUrl: string;
    gitCommit?: string;
}
export interface JenkinsPipelineStatus {
    projectId: string;
    buildNumber?: number;
    status: "QUEUED" | "RUNNING" | "SUCCESS" | "FAILED";
    url?: string;
}
function getJenkinsClient() {
    const baseUrl = process.env.JENKINS_URL;
    const user = process.env.JENKINS_USER;
    const token = process.env.JENKINS_TOKEN;
    if (!baseUrl || !user || !token) {
        throw new Error("Jenkins configuration missing (JENKINS_URL/USER/TOKEN).");
    }
    return axios.create({
        baseURL: baseUrl.replace(/\/+$/, ""),
        auth: {
            username: user,
            password: token,
        },
    });
}
export async function createPipelineJob(jobName: string, gitRepoUrl: string): Promise<void> {
    const client = getJenkinsClient();
    const configXml = `<?xml version='1.1' encoding='UTF-8'?>
<flow-definition plugin="workflow-job">
  <description>Generated by DevSecOps PaaS</description>
  <keepDependencies>false</keepDependencies>
  <definition class="org.jenkinsci.plugins.workflow.cps.CpsScmFlowDefinition" plugin="workflow-cps">
    <scm class="hudson.plugins.git.GitSCM" plugin="git">
      <configVersion>2</configVersion>
      <userRemoteConfigs>
        <hudson.plugins.git.UserRemoteConfig>
          <url>${gitRepoUrl}</url>
        </hudson.plugins.git.UserRemoteConfig>
      </userRemoteConfigs>
      <branches>
        <hudson.plugins.git.BranchSpec>
          <name>*/main</name>
        </hudson.plugins.git.BranchSpec>
      </branches>
      <doGenerateSubmoduleConfigurations>false</doGenerateSubmoduleConfigurations>
      <submoduleCfg class="empty-list" />
      <extensions />
    </scm>
    <scriptPath>Jenkinsfile</scriptPath>
    <lightweight>true</lightweight>
  </definition>
  <triggers />
  <disabled>false</disabled>
</flow-definition>`;
    await client.post(`/createItem`, configXml, {
        params: { name: jobName },
        headers: { "Content-Type": "application/xml" },
    });
}
export async function deleteJob(jobName: string): Promise<void> {
    const client = getJenkinsClient();
    try {
        await client.post(`/job/${encodeURIComponent(jobName)}/doDelete`);
    }
    catch {
    }
}
export async function triggerPipeline(input: JenkinsPipelineTrigger): Promise<JenkinsPipelineStatus> {
    const client = getJenkinsClient();
    const jobName = `project-${input.projectId}`;
    try {
        await client.post(`/job/${encodeURIComponent(jobName)}/buildWithParameters`, null, {
            params: {
                BRANCH: input.branch,
                GIT_REPO: input.gitRepoUrl,
                GIT_COMMIT: input.gitCommit,
            },
        });
        return {
            projectId: input.projectId,
            status: "QUEUED",
        };
    }
    catch (error) {
        const message = axios.isAxiosError(error) && error.response
            ? `Jenkins error: ${error.response.status} ${error.response.statusText}`
            : (error as Error).message;
        throw new Error(message);
    }
}
export async function getPipelineStatus(projectId: string, buildNumber: number): Promise<JenkinsPipelineStatus> {
    const client = getJenkinsClient();
    const jobName = `project-${projectId}`;
    try {
        const { data } = await client.get(`/job/${encodeURIComponent(jobName)}/${buildNumber}/api/json`);
        const result = (data.result as string | null) ?? null;
        let status: JenkinsPipelineStatus["status"] = "RUNNING";
        if (result === "SUCCESS")
            status = "SUCCESS";
        else if (result === "FAILURE" || result === "ABORTED")
            status = "FAILED";
        return {
            projectId,
            buildNumber,
            status,
            url: data.url as string | undefined,
        };
    }
    catch (error) {
        const message = axios.isAxiosError(error) && error.response
            ? `Jenkins error: ${error.response.status} ${error.response.statusText}`
            : (error as Error).message;
        throw new Error(message);
    }
}
export async function getBuildLogs(projectId: string, buildNumber: number): Promise<string> {
    const client = getJenkinsClient();
    const jobName = `project-${projectId}`;
    try {
        const { data } = await client.get(`/job/${encodeURIComponent(jobName)}/${buildNumber}/consoleText`, { responseType: "text" });
        return data as string;
    }
    catch (error) {
        const message = axios.isAxiosError(error) && error.response
            ? `Jenkins logs error: ${error.response.status} ${error.response.statusText}`
            : (error as Error).message;
        throw new Error(message);
    }
}
