import type { DeployPipelineReadiness } from "@/server/services/deploy-pipeline-readiness";
export type UserRole = "ADMIN" | "DEVELOPER";
export interface UserProfile {
    id: string;
    email: string;
    fullName: string;
    role: UserRole;
    accountKind?: "local" | "keycloak";
}
export interface LoginRequest {
    email: string;
    password: string;
}
export interface RegisterRequest {
    fullName: string;
    email: string;
    password: string;
    role: UserRole;
}
export interface AuthResponse {
    token?: string;
    user: UserProfile;
}
export interface AuthSessionResponse {
    authenticated: boolean;
    user: UserProfile | null;
}
export interface UpdateProfileRequest {
    fullName?: string;
    email?: string;
    currentPassword?: string;
    newPassword?: string;
}
export interface UpdateProfileResponse {
    user: UserProfile;
    message: string;
}
export interface AuthStatusResponse {
    success: boolean;
    email: string;
    message: string;
    requiresVerification: boolean;
    mailDelivery: "smtp" | "console" | "none";
}
export interface Project {
    id: string;
    projectName: string;
    gitRepositoryUrl: string;
    branch: string;
    gitCredentialsId?: string;
    language: string;
    buildProvider: "jenkins" | "tekton";
    buildProfile: "node" | "python" | "java" | "static" | "custom";
    buildMode: "platform-template" | "custom-dockerfile";
    buildTemplateName: string;
    buildTemplateVersion: string;
    buildDetectionReason: string;
    namespace: string;
    imageTag: string;
    lastDeploymentStatus: string;
    buildStatus: string;
    podStatus: string;
    createdAt: string;
    autoGenerateDockerfile: boolean;
    autoGenerateHelmChart: boolean;
    url: string;
    pendingGitHubPush?: PendingGitHubPush | null;
}
export interface PendingGitHubPush {
    branch: string;
    after: string;
    cloneUrl: string;
    fullName: string;
    receivedAt: string;
}
export interface ProjectRequest {
    projectName: string;
    gitRepositoryUrl: string;
    branch?: string;
    gitCredentialsId?: string;
    language: string;
    buildProfile?: "node" | "python" | "java" | "static" | "custom";
    autoGenerateDockerfile: boolean;
    autoGenerateHelmChart: boolean;
}
export interface CreateProjectResponse {
    project: Project;
    warnings: string[];
}
export interface RepositoryLanguageDetectionResponse {
    language: string;
    buildProfile: "node" | "python" | "java" | "static" | "custom";
    detectionReason: string;
    branch: string;
    hasDockerfile: boolean;
    suggestedDockerfile?: string;
}
export interface ActionResponse {
    status: string;
    message: string;
    buildProvider?: "jenkins" | "tekton";
    buildRunId?: string | null;
    buildLogUrl?: string;
    deploymentLogUrl?: string;
    deploymentId?: string;
}
export interface DeploymentPollResponse {
    id: string;
    projectId: string;
    status: string;
    logs: string;
    buildNumber: number | null;
    buildProvider: string | null;
    buildRunId: string | null;
    artifactImage: string | null;
    artifactDigest: string | null;
    url: string | null;
    failureReason: string | null;
    failureMessage: string | null;
}
export interface DeploymentSummary {
    id: string;
    status: string;
    createdAt: string;
    buildNumber: number | null;
    buildProvider: string | null;
    buildRunId: string | null;
    artifactImage: string | null;
    artifactDigest: string | null;
    url: string | null;
    failureReason: string | null;
    failureMessage: string | null;
}
export interface RecentDeploymentListItem {
    id: string;
    projectId: string;
    projectName: string;
    status: string;
    createdAt: string;
    buildNumber: number | null;
}
export interface RecentDeploymentsListResponse {
    jenkinsJobName: string;
    deployments: RecentDeploymentListItem[];
}
export interface DeployPipelineReadinessResponse {
    simulationEnabled: boolean;
    buildBackend: {
        selected: "jenkins" | "tekton";
        configured: boolean;
    };
    jenkins: {
        configured: boolean;
    };
    tekton: {
        configured: boolean;
        namespace: string;
        pipeline: string;
    };
    gitops: {
        configured: boolean;
    };
    argocd: {
        configured: boolean;
    };
    appsPublicUrl: {
        configured: boolean;
    };
    missingForFullPipeline: string[];
}
export interface DashboardOverviewResponse {
    stats: {
        totalProjects: number;
        totalDeployments: number;
        successRatePercent: number | null;
        activeDeployments: number;
        failedDeployments: number;
        runningPods: number;
        unhealthyPods: number;
        liveTools: number;
        degradedTools: number;
    };
    cluster: {
        pods: number;
        runningPods: number;
        services: number;
        deployments: number;
        healthyDeployments: number;
    };
    security: {
        score: number;
        critical: number;
        high: number;
        medium: number;
        low: number;
        unsignedImages: number;
        policyBlocked: number;
        dependencyTrack: SeverityBreakdown;
        trivy: SeverityBreakdown;
        sonar: {
            passed: number;
            failed: number;
            unknown: number;
        };
        opa: {
            violationCount: number;
            projectsWithViolations: number;
            projectsWithPolicyGap: number;
        };
        kyverno: {
            projectsWithPolicyGap: number;
        };
        sampledProjects: number;
    };
    artifacts: ArtifactRecord[];
    platformTools: PlatformToolGroup[];
    projects: {
        id: string;
        projectName: string;
        namespace: string;
        buildStatus: string;
        lastDeploymentStatus: string;
        podStatus: string;
        imageTag: string | null;
        url: string | null;
        updatedAt: string;
    }[];
    failedDeployments: {
        id: string;
        projectId: string;
        projectName: string;
        status: string;
        failureReason: string | null;
        failureMessage: string | null;
        createdAt: string;
    }[];
    recentDeployments: {
        id: string;
        projectId: string;
        projectName: string;
        status: string;
        createdAt: string;
    }[];
    clusterDataSource: "kubernetes" | "project_rollups" | "none";
}
export interface AppReachabilityResponse {
    url: string | null;
    reachable: boolean;
    statusCode: number | null;
    error?: string;
}
export interface ArtifactRecord {
    name: string;
    version: string;
    size: string;
    createdAt: string;
    downloadUrl: string | null;
    repository: string;
    path: string;
    status: "Stored";
}
export interface ArtifactListResponse {
    artifacts: ArtifactRecord[];
    latestArtifact: ArtifactRecord | null;
}
export interface SecurityMetrics {
    qualityGateStatus: string;
    dependencyTrack: SeverityBreakdown;
    dependencyTrackProjectUuid?: string | null;
    dependencyTrackProjectName?: string | null;
    dependencyTrackFindings?: DependencyTrackFinding[];
    securitySummary?: string;
    imageSecurity?: ImageSecurityStatus;
    securityEnforcement?: SecurityEnforcementStatus;
    trivy: SeverityBreakdown;
    cosignSigned: boolean;
    opaViolations: number;
    securityScore: number;
}
export interface SeverityBreakdown {
    critical: number;
    high: number;
    medium: number;
    low: number;
}
export interface DependencyTrackFinding {
    title: string;
    severity: "CRITICAL" | "HIGH" | "MEDIUM" | "LOW";
    component?: string | null;
    vulnerabilityId?: string | null;
    recommendation?: string | null;
}
export interface DependencyTrackMetricsResponse {
    projectId: string;
    projectName: string;
    projectUuid: string | null;
    metrics: SeverityBreakdown;
    findings: DependencyTrackFinding[];
    summary: string;
}
export interface ImageSecurityStatus {
    imageRef: string;
    signed: boolean;
    verified: boolean;
    verifier: "Cosign";
}
export interface SecurityEnforcementStatus {
    policyEngine: "Kyverno" | "OPA" | "Gatekeeper" | "None";
    policyValidated: boolean;
    deploymentAllowed: boolean;
    summary: string;
}
export interface RuntimeMetrics {
    cpuUsagePercent: number;
    memoryUsagePercent: number;
    runningApplications: number;
    failedBuilds: number;
    signedImages: number;
    unsignedImages: number;
}
export interface MonitoringSeriesPoint {
    ts: number;
    value: number;
}
export interface MonitoringKubernetesPod {
    name: string;
    namespace: string;
    containers: string[];
    status: string;
    health: string;
    healthReason: string;
    ready: string;
    restarts: number;
    nodeName: string;
    podIP: string;
    createdAt: string;
}
export interface ProjectMonitoringSnapshot {
    project: {
        id: string;
        projectName: string;
        namespace: string;
        imageTag: string;
        url: string;
        lastDeploymentStatus: string;
        buildStatus: string;
        podStatus: string;
    };
    runtime: RuntimeMetrics;
    prometheus: {
        configured: boolean;
        rangeError?: string;
        durationSeconds: number;
        stepSeconds: number;
        cpuSeries: MonitoringSeriesPoint[];
        memorySeries: MonitoringSeriesPoint[];
    };
    kubernetes: {
        configured: boolean;
        error?: string;
        summary: {
            running: number;
            failed: number;
            pending: number;
            succeeded: number;
            other: number;
            total: number;
        };
        pods: MonitoringKubernetesPod[];
    };
}
export interface DeploymentStatus {
    projectId: string;
    namespace: string;
    imageTag: string;
    podStatus: string;
    buildLogs: string;
    deploymentLogs: string;
    buildProvider?: "jenkins" | "tekton";
    buildProfile?: "node" | "python" | "java" | "static" | "custom";
    buildMode?: "platform-template" | "custom-dockerfile";
    lastDeploymentStatus: string;
}
export interface ContainerImageRecord {
    id: string;
    projectId: string;
    imageRef: string;
    registry: string;
    action: string;
    digest: string | null;
    createdAt: string;
}
export interface ArgoCdStatus {
    health: string;
    syncStatus: string;
    appName: string;
    unreachableReason?: string;
}
export type PlatformIntegrationCategoryId = "control-infra" | "security-policy" | "monitoring" | "cicd" | "registry" | "security-scan" | "infra" | "runtimes";
export type PlatformIntegrationKind = "external" | "internal" | "cli";
export type PlatformIntegrationReachabilityState = "reachable" | "unreachable" | "skipped";
export interface PlatformIntegrationReachability {
    state: PlatformIntegrationReachabilityState;
    latencyMs?: number;
    message?: string;
}
export interface PlatformIntegrationItem {
    id: string;
    name: string;
    description: string;
    kind: PlatformIntegrationKind;
    href: string | null;
    internalPath?: string;
    configured: boolean;
    optional?: boolean;
    notes?: string;
    reachability?: PlatformIntegrationReachability;
}
export interface PlatformIntegrationCategory {
    id: PlatformIntegrationCategoryId;
    title: string;
    description: string;
    items: PlatformIntegrationItem[];
}
export interface PlatformIntegrationsResponse {
    categories: PlatformIntegrationCategory[];
    meta: {
        policyEngine: string;
        kubernetesEnabled: boolean;
        buildBackend: string;
        harborConfigured: boolean;
        springBackendConfigured: boolean;
        deployReadiness: DeployPipelineReadiness;
    };
}
export type PlatformToolTone = "success" | "warning" | "danger" | "outline";
export interface PlatformToolItem {
    name: string;
    detail: string;
    tone: PlatformToolTone;
}
export interface PlatformToolGroup {
    title: string;
    items: PlatformToolItem[];
}
export interface PlatformToolingResponse {
    groups: PlatformToolGroup[];
}
