export type UserRole = "ADMIN" | "DEVELOPER";

export interface UserProfile {
  id: string;
  email: string;
  fullName: string;
  role: UserRole;
}

export interface LoginRequest {
  email: string;
  password: string;
}

export interface RegisterRequest {
  fullName: string;
  email: string;
  password: string;
  role: UserRole;
}

export interface AuthResponse {
  token: string;
  user: UserProfile;
}

export interface Project {
  id: string;
  projectName: string;
  gitRepositoryUrl: string;
  branch: string;
  language: string;
  namespace: string;
  imageTag: string;
  lastDeploymentStatus: string;
  buildStatus: string;
  podStatus: string;
  createdAt: string;
  autoGenerateDockerfile: boolean;
  autoGenerateHelmChart: boolean;
  /** Public app URL when a deploy has completed (e.g. https://my-app.apps.local). */
  url: string;
}

export interface ProjectRequest {
  projectName: string;
  gitRepositoryUrl: string;
  branch: string;
  language: string;
  autoGenerateDockerfile: boolean;
  autoGenerateHelmChart: boolean;
}

export interface ActionResponse {
  status: string;
  message: string;
  buildLogUrl?: string;
  deploymentLogUrl?: string;
  deploymentId?: string;
}

/** GET /api/deployments/[id] */
export interface DeploymentPollResponse {
  id: string;
  projectId: string;
  status: string;
  logs: string;
  buildNumber: number | null;
  url: string | null;
  failureReason: string | null;
  failureMessage: string | null;
}

/** GET /api/projects/[id]/deployments */
export interface DeploymentSummary {
  id: string;
  status: string;
  createdAt: string;
  buildNumber: number | null;
  url: string | null;
  failureReason: string | null;
  failureMessage: string | null;
}

/** GET /api/dashboard/overview */
export interface DashboardOverviewResponse {
  stats: {
    totalProjects: number;
    totalDeployments: number;
    successRatePercent: number | null;
    activeDeployments: number;
  };
  recentDeployments: {
    id: string;
    projectId: string;
    projectName: string;
    status: string;
    createdAt: string;
  }[];
}

/** GET /api/projects/[id]/app-reachability */
export interface AppReachabilityResponse {
  url: string | null;
  reachable: boolean;
  statusCode: number | null;
  error?: string;
}

export interface SecurityMetrics {
  qualityGateStatus: string;
  dependencyTrack: SeverityBreakdown;
  trivy: SeverityBreakdown;
  cosignSigned: boolean;
  opaViolations: number;
  securityScore: number;
}

export interface SeverityBreakdown {
  critical: number;
  high: number;
  medium: number;
  low: number;
}

export interface RuntimeMetrics {
  cpuUsagePercent: number;
  memoryUsagePercent: number;
  runningApplications: number;
  failedBuilds: number;
  signedImages: number;
  unsignedImages: number;
}

export interface DeploymentStatus {
  projectId: string;
  namespace: string;
  imageTag: string;
  podStatus: string;
  buildLogs: string;
  deploymentLogs: string;
  lastDeploymentStatus: string;
}

export interface ContainerImageRecord {
  id: string;
  projectId: string;
  imageRef: string;
  registry: string;
  action: string;
  digest: string | null;
  createdAt: string;
}

export interface ArgoCdStatus {
  health: string;
  syncStatus: string;
  appName: string;
}
