#!/usr/bin/env python3
"""
Reads frontend/.env and writes frontend/docker-compose.env (one KEY=value per line).

Usage (from paas/frontend):
  python3 scripts/flatten-env-for-compose.py
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

KEY_RE = re.compile(r"^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*)$")


def parse_loose_env(text: str) -> list[tuple[str, str]]:
    out: list[tuple[str, str]] = []
    current_key: str | None = None
    parts: list[str] = []

    def flush() -> None:
        nonlocal current_key, parts
        if current_key is not None:
            out.append((current_key, "\n".join(parts)))
        current_key = None
        parts = []

    for line in text.splitlines():
        t = line.rstrip("\r\n")
        if not t.strip() or t.lstrip().startswith("#"):
            continue
        m = KEY_RE.match(t)
        if m:
            flush()
            current_key = m.group(1)
            parts = [m.group(2)]
            continue
        if current_key is not None:
            parts.append(t)

    flush()
    return out


def escape_for_compose_line(value: str) -> str:
    needs_quote = (
        not value
        or any(c in value for c in "\r\n\"\\#")
        or "$" in value
        or re.search(r"\s", value) is not None
    )
    if not needs_quote:
        return value
    escaped = (
        value.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("\r\n", "\n")
        .replace("\r", "\n")
        .replace("\n", "\\n")
        .replace("$", "$$$$")
    )
    return f'"{escaped}"'


def main() -> int:
    root = Path(__file__).resolve().parent.parent
    input_path = Path(sys.argv[1]).resolve() if len(sys.argv) > 1 else root / ".env"
    output_path = Path(sys.argv[2]).resolve() if len(sys.argv) > 2 else root / "docker-compose.env"

    if not input_path.is_file():
        print(f"Missing {input_path}; copy .env.example first.", file=sys.stderr)
        return 1

    entries = parse_loose_env(input_path.read_text(encoding="utf-8"))
    header = """# Generated by scripts/flatten-env-for-compose.py — do not edit this file by hand.
# Source: frontend/.env  |  Regenerate: python3 scripts/flatten-env-for-compose.py
#
# If paas-frontend runs in Docker (paas/docker-compose.yml):
# - DATABASE_URL: use hostname `postgres` (compose DB) or `host.docker.internal` — never `localhost`.
# - APP_BASE_URL: port 3000 (image maps 3000:3000).
# - KUBE_CONFIG_PATH: /home/nextjs/.kube/config inside the container.
#
"""
    body = "\n".join(f"{k}={escape_for_compose_line(v)}" for k, v in entries)
    output_path.write_text(f"{header}{body}\n", encoding="utf-8")
    print(f"Wrote {output_path} ({len(entries)} variables)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
