apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: paas-{{projectName}}
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/nourhb/gitops
    path: apps/{{projectName}}
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: {{projectName}}
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
