import { resolveBuildPlan, type BuildProfile } from "@/server/build-planner";

export interface DeployProfileSpec {
    profile: BuildProfile;
    containerPort: number;
    probePath: string;
}

export function resolveDeployProfileSpec(profile: BuildProfile): DeployProfileSpec {
    switch (profile) {
        case "python":
            return { profile, containerPort: 8000, probePath: "/" };
        case "java":
            return { profile, containerPort: 8080, probePath: "/" };
        case "static":
            return { profile, containerPort: 80, probePath: "/" };
        case "node":
            return { profile, containerPort: 3000, probePath: "/" };
        default:
            return { profile: "custom", containerPort: 8080, probePath: "/" };
    }
}

export function resolveDeployProfileFromProject(input: {
    language?: string | null;
    gitRepositoryUrl?: string | null;
    autoGenerateDockerfile?: boolean | null;
}): DeployProfileSpec {
    const plan = resolveBuildPlan(input);
    return resolveDeployProfileSpec(plan.profile);
}
