import { resolveBuildPlan, type BuildProfile } from "@/server/build-planner";

export interface DeployProfileSpec {
    profile: BuildProfile;
    containerPort: number;
    probePath: string;
}

export function resolveDeployProfileSpec(profile: BuildProfile): DeployProfileSpec {
    switch (profile) {
        case "python":
            return { profile, containerPort: 8000, probePath: "/" };
        case "java":
            return { profile, containerPort: 8080, probePath: "/" };
        case "static":
            return { profile, containerPort: 80, probePath: "/" };
        case "node":
            return { profile, containerPort: 3000, probePath: "/" };
        default:
            return { profile: "custom", containerPort: 8080, probePath: "/" };
    }
}

export function resolveDeployProfileFromProject(input: {
    language?: string | null;
    gitRepositoryUrl?: string | null;
    autoGenerateDockerfile?: boolean | null;
}): DeployProfileSpec {
    const language = String(input.language ?? "").trim().toLowerCase();
    if (language.includes("angular")) {
        return { profile: "static", containerPort: 80, probePath: "/" };
    }
    if ((language.includes("react") || language.includes("vue") || language.includes("vite")) &&
        !language.includes("next") && !language.includes("nest") && !language.includes("express")) {
        return { profile: "static", containerPort: 80, probePath: "/" };
    }
    const plan = resolveBuildPlan(input);
    return resolveDeployProfileSpec(plan.profile);
}
