apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: paas-postgres
  namespace: devsecops-paas
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:16
  primaryUpdateStrategy: unsupervised
  storage:
    size: 20Gi
    storageClass: standard
  superuserSecret:
    name: paas-postgres-superuser
  bootstrap:
    initdb:
      database: paas
      owner: paas
      secret:
        name: paas-postgres-app
  monitoring:
    enablePodMonitor: true
  backup:
    retentionPolicy: "7d"
    barmanObjectStore:
      destinationPath: s3://replace-me/paas-postgres
      s3Credentials:
        accessKeyId:
          name: cnpg-backup-creds
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: cnpg-backup-creds
          key: ACCESS_SECRET_KEY
