apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: paas
spec:
  type: ExternalName
  externalName: postgres-service.databases.svc.cluster.local
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
