"use client";
import { FormEvent, useEffect, useState } from "react";
import { useParams, useRouter } from "next/navigation";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Checkbox } from "@/components/ui/checkbox";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Skeleton } from "@/components/ui/skeleton";
import { projectApi } from "@/lib/api";
export default function EditProjectPage() {
    const params = useParams<{
        id: string;
    }>();
    const router = useRouter();
    const queryClient = useQueryClient();
    const projectId = params.id;
    const [error, setError] = useState<string | null>(null);
    const projectQuery = useQuery({
        queryKey: ["project", projectId],
        queryFn: () => projectApi.getProject(projectId)
    });
    const mutation = useMutation({
        mutationFn: (body: Parameters<typeof projectApi.updateProject>[1]) => projectApi.updateProject(projectId, body),
        onSuccess: () => {
            queryClient.invalidateQueries({ queryKey: ["projects"] });
            queryClient.invalidateQueries({ queryKey: ["project", projectId] });
            toast.success("Project updated");
            router.push(`/projects/${projectId}`);
        },
        onError: () => {
            setError("Update failed. Check fields and permissions.");
            toast.error("Could not update project");
        }
    });
    useEffect(() => {
        setError(null);
    }, [projectId]);
    const onSubmit = (event: FormEvent<HTMLFormElement>) => {
        event.preventDefault();
        setError(null);
        const formData = new FormData(event.currentTarget);
        mutation.mutate({
            projectName: String(formData.get("projectName") || ""),
            gitRepositoryUrl: String(formData.get("gitRepositoryUrl") || ""),
            branch: String(formData.get("branch") || ""),
            gitCredentialsId: String(formData.get("gitCredentialsId") || ""),
            language: String(formData.get("language") || ""),
            autoGenerateDockerfile: Boolean(formData.get("autoGenerateDockerfile")),
            autoGenerateHelmChart: Boolean(formData.get("autoGenerateHelmChart"))
        });
    };
    if (projectQuery.isLoading) {
        return (<div className="mx-auto max-w-3xl space-y-4">
        <Skeleton className="h-10 w-48"/>
        <Skeleton className="h-64 w-full"/>
      </div>);
    }
    if (projectQuery.isError || !projectQuery.data) {
        return <p className="text-sm text-danger">Project not found or access denied.</p>;
    }
    const p = projectQuery.data;
    return (<div className="mx-auto max-w-3xl">
      <Card>
        <CardHeader>
          <CardTitle>Edit project</CardTitle>
        </CardHeader>
        <CardContent>
          <form onSubmit={onSubmit} className="space-y-5">
            <div className="space-y-2">
              <Label htmlFor="projectName">Project name</Label>
              <Input id="projectName" name="projectName" required defaultValue={p.projectName}/>
            </div>
            <div className="space-y-2">
              <Label htmlFor="gitRepositoryUrl">Git repository URL</Label>
              <Input id="gitRepositoryUrl" name="gitRepositoryUrl" required defaultValue={p.gitRepositoryUrl}/>
            </div>
            <div className="grid gap-4 md:grid-cols-2">
              <div className="space-y-2">
                <Label htmlFor="branch">Branch</Label>
                <Input id="branch" name="branch" required defaultValue={p.branch}/>
              </div>
              <div className="space-y-2">
                <Label htmlFor="language">Language / stack</Label>
                <Input id="language" name="language" required defaultValue={p.language}/>
              </div>
            </div>
            <div className="space-y-2">
              <Label htmlFor="gitCredentialsId">Git credentials (Jenkins)</Label>
              <Input id="gitCredentialsId" name="gitCredentialsId" defaultValue={p.gitCredentialsId || ""} placeholder="Optional: Jenkins credentialsId for private repos"/>
              <p className="text-xs text-muted">
                Only needed for private Git repositories. Leave blank for public repos.
              </p>
            </div>
            <div className="space-y-3 rounded-md border border-border p-4">
              <label className="flex items-center gap-3 text-sm">
                <Checkbox name="autoGenerateDockerfile" defaultChecked={p.autoGenerateDockerfile}/>
                Auto-generate Dockerfile
              </label>
              <label className="flex items-center gap-3 text-sm">
                <Checkbox name="autoGenerateHelmChart" defaultChecked={p.autoGenerateHelmChart}/>
                Auto-generate Helm chart
              </label>
            </div>
            {error ? <p className="text-sm text-danger">{error}</p> : null}
            <div className="flex gap-3">
              <Button disabled={mutation.isPending} type="submit">
                {mutation.isPending ? "Saving…" : "Save changes"}
              </Button>
              <Button type="button" variant="outline" onClick={() => router.back()}>
                Cancel
              </Button>
            </div>
          </form>
        </CardContent>
      </Card>
    </div>);
}
