"use client";

import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
import { useMutation } from "@tanstack/react-query";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Checkbox } from "@/components/ui/checkbox";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { projectApi } from "@/lib/api";

export default function CreateProjectPage() {
  const router = useRouter();
  const [error, setError] = useState<string | null>(null);

  const mutation = useMutation({
    mutationFn: projectApi.createProject,
    onSuccess: (project) => {
      toast.success("Project and Jenkins job scaffold created");
      router.push(`/projects/${project.id}`);
    },
    onError: () => {
      setError("Unable to create project and pipeline.");
      toast.error("Create project failed");
    }
  });

  const onSubmit = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    setError(null);
    const formData = new FormData(event.currentTarget);

    mutation.mutate({
      projectName: String(formData.get("projectName") || ""),
      gitRepositoryUrl: String(formData.get("gitRepositoryUrl") || ""),
      branch: String(formData.get("branch") || "main"),
      language: String(formData.get("language") || "Spring Boot"),
      autoGenerateDockerfile: Boolean(formData.get("autoGenerateDockerfile")),
      autoGenerateHelmChart: Boolean(formData.get("autoGenerateHelmChart"))
    });
  };

  return (
    <div className="mx-auto max-w-3xl">
      <Card>
        <CardHeader>
          <CardTitle>Create DevSecOps Project</CardTitle>
        </CardHeader>
        <CardContent>
          <form onSubmit={onSubmit} className="space-y-5">
            <div className="space-y-2">
              <Label htmlFor="projectName">Project Name</Label>
              <Input id="projectName" name="projectName" required />
            </div>

            <div className="space-y-2">
              <Label htmlFor="gitRepositoryUrl">Git Repository URL</Label>
              <Input id="gitRepositoryUrl" name="gitRepositoryUrl" required placeholder="https://github.com/org/repo" />
            </div>

            <div className="grid gap-4 md:grid-cols-2">
              <div className="space-y-2">
                <Label htmlFor="branch">Branch</Label>
                <Input id="branch" name="branch" defaultValue="main" required />
              </div>
              <div className="space-y-2">
                <Label htmlFor="language">Language</Label>
                <Input id="language" name="language" defaultValue="Spring Boot" required />
              </div>
            </div>

            <div className="space-y-3 rounded-md border border-border p-4">
              <label className="flex items-center gap-3 text-sm">
                <Checkbox name="autoGenerateDockerfile" defaultChecked />
                Auto-generate Dockerfile
              </label>
              <label className="flex items-center gap-3 text-sm">
                <Checkbox name="autoGenerateHelmChart" defaultChecked />
                Auto-generate Helm chart
              </label>
            </div>

            {error ? <p className="text-sm text-danger">{error}</p> : null}
            <Button disabled={mutation.isPending} type="submit" className="w-full">
              {mutation.isPending ? "Provisioning pipeline..." : "Create Project"}
            </Button>
          </form>
        </CardContent>
      </Card>
    </div>
  );
}
