"use client";
import { FormEvent, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { useMutation } from "@tanstack/react-query";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Checkbox } from "@/components/ui/checkbox";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { projectApi } from "@/lib/api";
import { parseBuildEnvText } from "@/lib/project-build-env";
import { queryHttpMessage } from "@/lib/query-http-message";
import type { BuildProfile } from "@/server/build-planner";
function inferBuildProfileFromLanguage(language: string): BuildProfile {
    const value = language.trim().toLowerCase();
    if (/(next|node|react|vue|angular|javascript|typescript|nest)/.test(value)) {
        return "node";
    }
    if (/(python|django|flask|fastapi|poetry|pip)/.test(value)) {
        return "python";
    }
    if (/(java|spring|maven|gradle|kotlin)/.test(value)) {
        return "java";
    }
    if (/(static|html|nginx|spa)/.test(value)) {
        return "static";
    }
    return "custom";
}
export default function CreateProjectPage() {
    const router = useRouter();
    const [error, setError] = useState<string | null>(null);
    const [gitRepositoryUrl, setGitRepositoryUrl] = useState("");
    const [branch, setBranch] = useState("");
    const [gitCredentialsId, setGitCredentialsId] = useState("");
    const [language, setLanguage] = useState("");
    const [detectionReason, setDetectionReason] = useState("");
    const [isDetectingLanguage, setIsDetectingLanguage] = useState(false);
    const [autoGenerateDockerfile, setAutoGenerateDockerfile] = useState(true);
    const [buildProfileFromApi, setBuildProfileFromApi] = useState<BuildProfile | null>(null);
    const [repoHasDockerfile, setRepoHasDockerfile] = useState<boolean | null>(null);
    const [dockerfileDraft, setDockerfileDraft] = useState("");
    const [dockerfileAcknowledged, setDockerfileAcknowledged] = useState(false);
    const [webhookUrl, setWebhookUrl] = useState("");
    const [buildEnvText, setBuildEnvText] = useState("");
    const buildProfile = buildProfileFromApi ?? inferBuildProfileFromLanguage(language);
    const buildMode = buildProfile === "custom" || !autoGenerateDockerfile ? "Custom Dockerfile contract" : "Platform-managed template";
    const mutation = useMutation({
        mutationFn: projectApi.createProject,
        onSuccess: (res) => {
            const { project, warnings } = res;
            if (warnings.length > 0) {
                for (const w of warnings) {
                    toast.warning(w, { duration: 12000 });
                }
            }
            toast.success("Project created with build profile detection");
            router.push(`/projects/${project.id}`);
        },
        onError: (err) => {
            setError(queryHttpMessage(err, "Unable to create project."));
            toast.error("Create project failed");
        }
    });
    useEffect(() => {
        try {
            setWebhookUrl(`${window.location.origin}/api/webhooks/github`);
        }
        catch {
            setWebhookUrl("");
        }
    }, []);
    useEffect(() => {
        const repo = gitRepositoryUrl.trim();
        const currentBranch = branch.trim();
        if (!/^https?:\/\/github\.com\/.+/i.test(repo) && !/^git@github\.com:.+/i.test(repo)) {
            setIsDetectingLanguage(false);
            setDetectionReason("");
            setBuildProfileFromApi(null);
            setRepoHasDockerfile(null);
            return;
        }
        let cancelled = false;
        setIsDetectingLanguage(true);
        setRepoHasDockerfile(null);
        const timer = window.setTimeout(async () => {
            try {
                const detected = await projectApi.detectLanguage(repo, currentBranch || undefined);
                if (cancelled) {
                    return;
                }
                setLanguage(detected.language);
                setDetectionReason(detected.detectionReason);
                setBuildProfileFromApi(detected.buildProfile);
                setRepoHasDockerfile(detected.hasDockerfile);
                setDockerfileDraft(detected.suggestedDockerfile ?? "");
                setDockerfileAcknowledged(detected.hasDockerfile);
                if (detected.branch && detected.branch !== branch) {
                    setBranch(detected.branch);
                }
            }
            catch (err) {
                if (cancelled) {
                    return;
                }
                setBuildProfileFromApi(null);
                setRepoHasDockerfile(null);
                setDetectionReason(queryHttpMessage(err, "Could not auto-detect the stack from this repository."));
            }
            finally {
                if (!cancelled) {
                    setIsDetectingLanguage(false);
                }
            }
        }, 600);
        return () => {
            cancelled = true;
            window.clearTimeout(timer);
        };
    }, [gitRepositoryUrl, branch]);
    const onSubmit = (event: FormEvent<HTMLFormElement>) => {
        event.preventDefault();
        setError(null);
        if (repoHasDockerfile === false && !dockerfileAcknowledged) {
            toast.error("Confirm Dockerfile in repository before continuing.");
            return;
        }
        const formData = new FormData(event.currentTarget);
        mutation.mutate({
            projectName: String(formData.get("projectName") || ""),
            gitRepositoryUrl: gitRepositoryUrl.trim(),
            branch: branch.trim() || undefined,
            gitCredentialsId: gitCredentialsId.trim() || undefined,
            language: language.trim(),
            autoGenerateDockerfile: Boolean(formData.get("autoGenerateDockerfile")),
            autoGenerateHelmChart: Boolean(formData.get("autoGenerateHelmChart")),
            buildEnv: parseBuildEnvText(buildEnvText)
        });
    };
    const copyDockerfile = async () => {
        try {
            await navigator.clipboard.writeText(dockerfileDraft);
            toast.success("Dockerfile copied to clipboard");
        }
        catch {
            toast.error("Could not copy to clipboard");
        }
    };
    const copyWebhookUrl = async () => {
        if (!webhookUrl) {
            toast.error("Webhook URL is not available yet.");
            return;
        }
        try {
            await navigator.clipboard.writeText(webhookUrl);
            toast.success("Webhook URL copied");
        }
        catch {
            toast.error("Could not copy");
        }
    };
    return (<div className="mx-auto max-w-3xl">
      <Card>
        <CardHeader>
          <CardTitle>Create DevSecOps Project</CardTitle>
        </CardHeader>
        <CardContent>
          <form onSubmit={onSubmit} className="space-y-5">
            <div className="space-y-2">
              <Label htmlFor="projectName">Project Name</Label>
              <Input id="projectName" name="projectName" required/>
            </div>

            <div className="space-y-2">
              <Label htmlFor="gitRepositoryUrl">Git Repository URL</Label>
              <Input id="gitRepositoryUrl" name="gitRepositoryUrl" required placeholder="https://github.com/org/repo" value={gitRepositoryUrl} onChange={(event) => setGitRepositoryUrl(event.target.value)}/>
            </div>

            <div className="grid gap-4 md:grid-cols-2">
              <div className="space-y-2">
                <Label htmlFor="branch">Branch</Label>
                <Input id="branch" name="branch" value={branch} onChange={(event) => setBranch(event.target.value)} placeholder="Auto-detect from repository"/>
              </div>
              <div className="space-y-2">
                <Label htmlFor="gitCredentialsId">Git credentials (Jenkins)</Label>
                <Input id="gitCredentialsId" name="gitCredentialsId" value={gitCredentialsId} onChange={(event) => setGitCredentialsId(event.target.value)} placeholder="credentialsId"/>
              </div>
              <div className="space-y-2 md:col-span-2">
                <Label htmlFor="language">Language</Label>
                <Input id="language" name="language" value={language} onChange={(event) => {
            setLanguage(event.target.value);
            setBuildProfileFromApi(null);
        }} placeholder={isDetectingLanguage ? "Detecting…" : "Language"} required/>
                {detectionReason ? <p className="text-xs text-muted">{isDetectingLanguage ? "Detecting…" : detectionReason}</p> : null}
                {repoHasDockerfile === true ? <p className="text-xs text-emerald-600 dark:text-emerald-400">Dockerfile found</p> : null}
                {repoHasDockerfile === false ? <p className="text-xs text-amber-700 dark:text-amber-400">No Dockerfile</p> : null}
              </div>
            </div>

            <div className="space-y-2 rounded-md border border-border p-4">
              <div className="flex items-end gap-2">
                <div className="flex-1 space-y-1">
                  <Label htmlFor="githubWebhookUrl">GitHub webhook URL</Label>
                  <Input id="githubWebhookUrl" value={webhookUrl} readOnly/>
                </div>
                <Button type="button" variant="outline" size="sm" onClick={copyWebhookUrl}>
                  Copy
                </Button>
              </div>
            </div>

            {repoHasDockerfile === false ? <div className="space-y-3 rounded-md border border-border p-4">
              <div className="flex flex-wrap items-center justify-between gap-2">
                <Label htmlFor="dockerfileDraft" className="text-sm font-medium">
                  Dockerfile
                </Label>
                <Button type="button" variant="outline" size="sm" onClick={copyDockerfile}>
                  Copy
                </Button>
              </div>
              <Textarea id="dockerfileDraft" value={dockerfileDraft} onChange={(e) => setDockerfileDraft(e.target.value)} className="min-h-[220px] font-mono text-xs" spellCheck={false}/>
              <label className="flex items-center gap-3 text-sm">
                <Checkbox checked={dockerfileAcknowledged} onChange={(event) => setDockerfileAcknowledged(event.target.checked)}/>
                <span>Dockerfile in repository</span>
              </label>
            </div> : null}

            <div className="space-y-3 rounded-md border border-border p-4">
              <label className="flex items-center gap-3 text-sm">
                <Checkbox name="autoGenerateDockerfile" checked={autoGenerateDockerfile} onChange={(event) => setAutoGenerateDockerfile(event.target.checked)}/>
                Platform-managed build template
              </label>
              <label className="flex items-center gap-3 text-sm">
                <Checkbox name="autoGenerateHelmChart" defaultChecked/>
                Auto-generate Helm chart
              </label>
              <div className="rounded-md bg-muted/40 p-3 text-sm">
                <p>
                  Build profile: <span className="font-medium text-foreground">{buildProfile}</span>
                </p>
                <p>
                  Build mode: <span className="font-medium text-foreground">{buildMode}</span>
                </p>
              </div>
            </div>

            <div className="space-y-2 rounded-md border border-border p-4">
              <Label htmlFor="buildEnv">Application environment (.env) — optional</Label>
              <p className="text-xs text-muted">
                Paste KEY=value lines (e.g. NEXT_PUBLIC_FIREBASE_* for Next.js). Stored encrypted in the database and injected at Jenkins build time. Not committed to Git.
              </p>
              <Textarea
                id="buildEnv"
                name="buildEnv"
                rows={8}
                className="font-mono text-xs"
                spellCheck={false}
                value={buildEnvText}
                onChange={(event) => setBuildEnvText(event.target.value)}
                placeholder={"NEXT_PUBLIC_FIREBASE_API_KEY=...\nNEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=..."}
              />
            </div>

            {error ? <p className="text-sm text-danger">{error}</p> : null}
            <Button disabled={mutation.isPending} type="submit" className="w-full">
              {mutation.isPending ? "Creating…" : "Create Project"}
            </Button>
          </form>
        </CardContent>
      </Card>
    </div>);
}
