"use client";
import { FormEvent, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { useMutation } from "@tanstack/react-query";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Checkbox } from "@/components/ui/checkbox";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { projectApi } from "@/lib/api";
import { queryHttpMessage } from "@/lib/query-http-message";
import type { BuildProfile } from "@/server/build-planner";
function inferBuildProfileFromLanguage(language: string): BuildProfile {
    const value = language.trim().toLowerCase();
    if (/(next|node|react|vue|angular|javascript|typescript|nest)/.test(value)) {
        return "node";
    }
    if (/(python|django|flask|fastapi|poetry|pip)/.test(value)) {
        return "python";
    }
    if (/(java|spring|maven|gradle|kotlin)/.test(value)) {
        return "java";
    }
    if (/(static|html|nginx|spa)/.test(value)) {
        return "static";
    }
    return "custom";
}
export default function CreateProjectPage() {
    const router = useRouter();
    const [error, setError] = useState<string | null>(null);
    const [gitRepositoryUrl, setGitRepositoryUrl] = useState("");
    const [branch, setBranch] = useState("main");
    const [gitCredentialsId, setGitCredentialsId] = useState("");
    const [language, setLanguage] = useState("");
    const [detectionReason, setDetectionReason] = useState("Paste a GitHub repository URL to auto-detect the stack.");
    const [isDetectingLanguage, setIsDetectingLanguage] = useState(false);
    const [autoGenerateDockerfile, setAutoGenerateDockerfile] = useState(true);
    const [buildProfileFromApi, setBuildProfileFromApi] = useState<BuildProfile | null>(null);
    const [repoHasDockerfile, setRepoHasDockerfile] = useState<boolean | null>(null);
    const [dockerfileDraft, setDockerfileDraft] = useState("");
    const [dockerfileAcknowledged, setDockerfileAcknowledged] = useState(false);
    const [webhookUrl, setWebhookUrl] = useState("");
    const [webhookSecret, setWebhookSecret] = useState("");
    const buildProfile = buildProfileFromApi ?? inferBuildProfileFromLanguage(language);
    const buildMode = buildProfile === "custom" || !autoGenerateDockerfile ? "Custom Dockerfile contract" : "Platform-managed template";
    const mutation = useMutation({
        mutationFn: projectApi.createProject,
        onSuccess: (res) => {
            const { project, warnings } = res;
            if (warnings.length > 0) {
                for (const w of warnings) {
                    toast.warning(w, { duration: 12000 });
                }
            }
            toast.success("Project created with build profile detection");
            router.push(`/projects/${project.id}`);
        },
        onError: (err) => {
            setError(queryHttpMessage(err, "Unable to create project."));
            toast.error("Create project failed");
        }
    });
    useEffect(() => {
        try {
            setWebhookUrl(`${window.location.origin}/api/webhooks/github`);
        }
        catch {
            setWebhookUrl("");
        }
    }, []);
    useEffect(() => {
        const repo = gitRepositoryUrl.trim();
        const currentBranch = branch.trim() || "main";
        if (!/^https?:\/\/github\.com\/.+/i.test(repo) && !/^git@github\.com:.+/i.test(repo)) {
            setIsDetectingLanguage(false);
            setDetectionReason("Paste a GitHub repository URL to auto-detect the stack.");
            setBuildProfileFromApi(null);
            setRepoHasDockerfile(null);
            return;
        }
        let cancelled = false;
        setIsDetectingLanguage(true);
        setRepoHasDockerfile(null);
        const timer = window.setTimeout(async () => {
            try {
                const detected = await projectApi.detectLanguage(repo, currentBranch);
                if (cancelled) {
                    return;
                }
                setLanguage(detected.language);
                setDetectionReason(detected.detectionReason);
                setBuildProfileFromApi(detected.buildProfile);
                setRepoHasDockerfile(detected.hasDockerfile);
                setDockerfileDraft(detected.suggestedDockerfile ?? "");
                setDockerfileAcknowledged(detected.hasDockerfile);
                if (detected.branch && detected.branch !== branch) {
                    setBranch(detected.branch);
                }
            }
            catch (err) {
                if (cancelled) {
                    return;
                }
                setBuildProfileFromApi(null);
                setRepoHasDockerfile(null);
                setDetectionReason(queryHttpMessage(err, "Could not auto-detect the stack from this repository."));
            }
            finally {
                if (!cancelled) {
                    setIsDetectingLanguage(false);
                }
            }
        }, 600);
        return () => {
            cancelled = true;
            window.clearTimeout(timer);
        };
    }, [gitRepositoryUrl, branch]);
    const onSubmit = (event: FormEvent<HTMLFormElement>) => {
        event.preventDefault();
        setError(null);
        if (repoHasDockerfile === false && !dockerfileAcknowledged) {
            toast.error("Confirm that you will add the Dockerfile to the repository before continuing.");
            return;
        }
        const formData = new FormData(event.currentTarget);
        mutation.mutate({
            projectName: String(formData.get("projectName") || ""),
            gitRepositoryUrl: gitRepositoryUrl.trim(),
            branch: branch.trim() || "main",
            gitCredentialsId: gitCredentialsId.trim() || undefined,
            language: language.trim(),
            autoGenerateDockerfile: Boolean(formData.get("autoGenerateDockerfile")),
            autoGenerateHelmChart: Boolean(formData.get("autoGenerateHelmChart"))
        });
    };
    const copyDockerfile = async () => {
        try {
            await navigator.clipboard.writeText(dockerfileDraft);
            toast.success("Dockerfile copied to clipboard");
        }
        catch {
            toast.error("Could not copy to clipboard");
        }
    };
    const copyWebhookUrl = async () => {
        if (!webhookUrl) {
            toast.error("Webhook URL is not available yet.");
            return;
        }
        try {
            await navigator.clipboard.writeText(webhookUrl);
            toast.success("Webhook URL copied");
        }
        catch {
            toast.error("Could not copy");
        }
    };
    const copyWebhookSecret = async () => {
        if (!webhookSecret.trim()) {
            toast.error("Enter a webhook secret first.");
            return;
        }
        try {
            await navigator.clipboard.writeText(webhookSecret.trim());
            toast.success("Webhook secret copied");
        }
        catch {
            toast.error("Could not copy");
        }
    };
    return (<div className="mx-auto max-w-3xl">
      <Card>
        <CardHeader>
          <CardTitle>Create DevSecOps Project</CardTitle>
        </CardHeader>
        <CardContent>
          <form onSubmit={onSubmit} className="space-y-5">
            <div className="space-y-2">
              <Label htmlFor="projectName">Project Name</Label>
              <Input id="projectName" name="projectName" required/>
            </div>

            <div className="space-y-2">
              <Label htmlFor="gitRepositoryUrl">Git Repository URL</Label>
              <Input id="gitRepositoryUrl" name="gitRepositoryUrl" required placeholder="https://github.com/org/repo" value={gitRepositoryUrl} onChange={(event) => setGitRepositoryUrl(event.target.value)}/>
            </div>

            <div className="grid gap-4 md:grid-cols-2">
              <div className="space-y-2">
                <Label htmlFor="branch">Branch</Label>
                <Input id="branch" name="branch" value={branch} onChange={(event) => setBranch(event.target.value)} required/>
              </div>
              <div className="space-y-2">
                <Label htmlFor="gitCredentialsId">Git credentials (Jenkins)</Label>
                <Input id="gitCredentialsId" name="gitCredentialsId" value={gitCredentialsId} onChange={(event) => setGitCredentialsId(event.target.value)} placeholder="Optional: Jenkins credentialsId for private repos"/>
                <p className="text-xs text-muted">
                  If your repository is private, set a Jenkins credential and paste its <code className="inline-code">credentialsId</code> here.
                </p>
              </div>
              <div className="space-y-2 md:col-span-2">
                <Label htmlFor="language">Language</Label>
                <Input id="language" name="language" value={language} onChange={(event) => {
            setLanguage(event.target.value);
            setBuildProfileFromApi(null);
        }} placeholder="Detected from repository" required/>
                <p className="text-xs text-muted">
                  {isDetectingLanguage ? "Detecting repository stack..." : detectionReason}
                </p>
                {repoHasDockerfile === true ? <p className="text-xs text-emerald-600 dark:text-emerald-400">
                  Dockerfile or Containerfile found at the repository root.
                </p> : null}
                {repoHasDockerfile === false ? <p className="text-xs text-amber-700 dark:text-amber-400">
                  No Dockerfile or Containerfile at the repository root on this branch. Review the suggestion below, commit it as Dockerfile, then confirm.
                </p> : null}
              </div>
            </div>

            <div className="space-y-3 rounded-md border border-border p-4">
              <div className="space-y-1">
                <p className="text-sm font-medium">GitHub Webhook (auto-build on push)</p>
                <p className="text-xs text-muted">
                  Create a webhook in your GitHub repo and select the <span className="font-medium text-foreground">push</span> event.
                </p>
              </div>

              <div className="space-y-2">
                <div className="flex items-end gap-2">
                  <div className="flex-1 space-y-1">
                    <Label htmlFor="githubWebhookUrl">Payload URL</Label>
                    <Input id="githubWebhookUrl" value={webhookUrl} readOnly placeholder="http://localhost:3001/api/webhooks/github"/>
                  </div>
                  <Button type="button" variant="outline" size="sm" onClick={copyWebhookUrl}>
                    Copy
                  </Button>
                </div>
                <p className="text-xs text-muted">
                  Content type: <span className="font-medium text-foreground">application/json</span>
                </p>
              </div>

              <div className="space-y-2">
                <div className="flex items-end gap-2">
                  <div className="flex-1 space-y-1">
                    <Label htmlFor="githubWebhookSecret">Secret</Label>
                    <Input id="githubWebhookSecret" value={webhookSecret} onChange={(e) => setWebhookSecret(e.target.value)} placeholder="Must match GITHUB_WEBHOOK_SECRET on the PaaS server"/>
                  </div>
                  <Button type="button" variant="outline" size="sm" onClick={copyWebhookSecret}>
                    Copy
                  </Button>
                </div>
                <p className="text-xs text-muted">
                  This is not stored in the project. Set the same value on the server as{" "}
                  <code className="inline-code">GITHUB_WEBHOOK_SECRET</code>.
                </p>
              </div>
            </div>

            {repoHasDockerfile === false ? <div className="space-y-3 rounded-md border border-border p-4">
              <div className="flex flex-wrap items-center justify-between gap-2">
                <Label htmlFor="dockerfileDraft" className="text-sm font-medium">
                  Suggested Dockerfile (edit before copying into your repo)
                </Label>
                <Button type="button" variant="outline" size="sm" onClick={copyDockerfile}>
                  Copy
                </Button>
              </div>
              <Textarea id="dockerfileDraft" value={dockerfileDraft} onChange={(e) => setDockerfileDraft(e.target.value)} className="min-h-[220px] font-mono text-xs" spellCheck={false}/>
              <label className="flex items-start gap-3 text-sm">
                <Checkbox checked={dockerfileAcknowledged} onChange={(event) => setDockerfileAcknowledged(event.target.checked)} className="mt-0.5"/>
                <span>I will add this file to the repository root as <code className="inline-code">Dockerfile</code> before running a build or deploy.</span>
              </label>
            </div> : null}

            <div className="space-y-3 rounded-md border border-border p-4">
              <label className="flex items-center gap-3 text-sm">
                <Checkbox name="autoGenerateDockerfile" checked={autoGenerateDockerfile} onChange={(event) => setAutoGenerateDockerfile(event.target.checked)}/>
                Prefer platform-managed build template
              </label>
              <label className="flex items-center gap-3 text-sm">
                <Checkbox name="autoGenerateHelmChart" defaultChecked/>
                Auto-generate Helm chart
              </label>
              <div className="rounded-md bg-muted/40 p-3 text-sm">
                <p>
                  Detected build profile: <span className="font-medium text-foreground">{buildProfile}</span>
                </p>
                <p>
                  Build mode: <span className="font-medium text-foreground">{buildMode}</span>
                </p>
              </div>
            </div>

            {error ? <p className="text-sm text-danger">{error}</p> : null}
            <Button disabled={mutation.isPending} type="submit" className="w-full">
              {mutation.isPending ? "Provisioning build path..." : "Create Project"}
            </Button>
          </form>
        </CardContent>
      </Card>
    </div>);
}
