import { beforeEach, describe, expect, it, vi } from "vitest";
const tektonApiMock = vi.hoisted(() => ({
    createNamespacedCustomObject: vi.fn().mockResolvedValue({})
}));
vi.mock("@/server/integrations/kubernetes-client", () => ({
    isKubernetesConfigured: vi.fn(() => true),
    getCustomObjectsApi: vi.fn(() => tektonApiMock),
    listPodsByLabel: vi.fn(async () => []),
    readPodLog: vi.fn(async () => null)
}));
const prismaMock = vi.hoisted(() => ({
    deployment: {
        update: vi.fn(async (args: unknown) => args)
    },
    containerImage: {
        create: vi.fn(async (args: unknown) => args)
    }
}));
const updateProjectMock = vi.hoisted(() => vi.fn(async () => ({})));
const commitHelmValuesGitHubMock = vi.hoisted(() => vi.fn(async () => ({ ref: "git-sha" })));
const syncArgoApplicationMock = vi.hoisted(() => vi.fn(async () => ({ logs: "[argocd] synced" })));
const buildAppPublicUrlMock = vi.hoisted(() => vi.fn(() => "https://app.example.com"));
vi.mock("@/server/db/prisma", () => ({
    prisma: prismaMock
}));
vi.mock("@/server/projects/project-service", () => ({
    updateProject: updateProjectMock
}));
vi.mock("@/server/gitops/gitops-github-service", () => ({
    commitHelmValuesGitHub: commitHelmValuesGitHubMock
}));
vi.mock("@/server/services/argocd-service", () => ({
    syncArgoApplication: syncArgoApplicationMock
}));
vi.mock("@/server/deploy/app-public-url", () => ({
    buildAppPublicUrl: buildAppPublicUrlMock
}));
import { prependBuildMetadata, parseBuildMetadata } from "@/server/build-metadata";
import { resolveBuildPlan } from "@/server/build-planner";
import { TektonBuildBackend } from "@/server/build-backend-tekton";
import { promoteDeploymentAfterBuildSuccess } from "@/server/services/cluster-deploy-service";
describe("enterprise build modernization", () => {
    beforeEach(() => {
        vi.clearAllMocks();
    });
    it("detects a managed Node build profile", () => {
        const plan = resolveBuildPlan({
            language: "Next.js",
            gitRepositoryUrl: "https://github.com/acme/web",
            autoGenerateDockerfile: true
        });
        expect(plan.profile).toBe("node");
        expect(plan.mode).toBe("platform-template");
        expect(plan.templateName).toBe("node-service");
    });
    it("round-trips provider-neutral build metadata", () => {
        const plan = resolveBuildPlan({
            language: "node",
            gitRepositoryUrl: "https://github.com/acme/web",
            autoGenerateDockerfile: true
        });
        const logs = prependBuildMetadata("build started", plan, {
            runId: "run-42",
            runNumber: 42,
            artifactImage: "harbor.example.com/paas/web:run-42",
            artifactDigest: "sha256:abc123"
        });
        const metadata = parseBuildMetadata(logs);
        expect(metadata.provider).toBe(plan.provider);
        expect(metadata.runId).toBe("run-42");
        expect(metadata.runNumber).toBe(42);
        expect(metadata.artifactDigest).toBe("sha256:abc123");
    });
    it("creates a Tekton PipelineRun for a managed deployment", async () => {
        const backend = new TektonBuildBackend();
        const plan = resolveBuildPlan({
            language: "node",
            gitRepositoryUrl: "https://github.com/acme/web",
            autoGenerateDockerfile: true
        });
        const result = await backend.triggerDeployment({
            id: "p1",
            projectName: "acme-web",
            gitRepositoryUrl: "https://github.com/acme/web",
            branch: "main",
            language: "node",
            autoGenerateDockerfile: true,
            autoGenerateHelmChart: true,
            namespace: "acme-web"
        }, plan);
        expect(result.provider).toBe("tekton");
        expect(result.runId).toBeTruthy();
        expect(result.artifactImage).toContain("acme-web");
        expect(tektonApiMock.createNamespacedCustomObject).toHaveBeenCalledTimes(1);
    });
    it("promotes artifact-first deployments using image digest metadata", async () => {
        await promoteDeploymentAfterBuildSuccess("d1", "p1", "acme-web", {
            provider: "tekton",
            runId: "run-42",
            runNumber: null,
            artifactImage: "harbor.example.com/paas/acme-web:run-42",
            artifactDigest: "sha256:abc123",
            buildLogTail: "[tekton] build succeeded"
        });
        expect(commitHelmValuesGitHubMock).toHaveBeenCalledWith("acme-web", "harbor.example.com/paas/acme-web:run-42@sha256:abc123");
        expect(updateProjectMock).toHaveBeenCalledWith("p1", expect.objectContaining({
            imageTag: "harbor.example.com/paas/acme-web:run-42@sha256:abc123",
            lastDeploymentStatus: "DEPLOYED"
        }));
    });
});
