export interface UserRecord {
    id: string;
    email: string;
    fullName?: string;
    passwordHash: string;
    role: "ADMIN" | "DEVELOPER";
}
export interface ProjectRecord {
    id: string;
    projectName: string;
    gitRepositoryUrl: string;
    branch: string;
    language: string;
    autoGenerateDockerfile: boolean;
    autoGenerateHelmChart: boolean;
    createdById: string;
}
export const db = {
    users: new Map<string, UserRecord>(),
    projects: new Map<string, ProjectRecord>()
};
