import { randomUUID } from "node:crypto";
import { vi } from "vitest";
export const dbState = {
    projects: [] as Record<string, unknown>[],
    deployments: [] as Record<string, unknown>[]
};
export function seedDefaultProject() {
    dbState.projects.length = 0;
    dbState.deployments.length = 0;
    dbState.projects.push({
        id: "p1",
        projectName: "e2e-demo",
        gitRepositoryUrl: "https://github.com/org/repo.git",
        branch: "main",
        language: "node",
        autoGenerateDockerfile: false,
        autoGenerateHelmChart: false,
        namespace: "e2e-demo",
        imageTag: null,
        buildStatus: "NOT_STARTED",
        lastDeploymentStatus: "NOT_DEPLOYED",
        podStatus: "UNKNOWN",
        buildLogs: null,
        deploymentLogs: null,
        url: null,
        createdAt: new Date(),
        updatedAt: new Date(),
        createdById: "u1"
    });
}
export function createPrismaMock() {
    return {
        $queryRawUnsafe: vi.fn(async () => [{ "?column?": 1 }]),
        project: {
            findFirst: vi.fn(async ({ where }: {
                where?: Record<string, unknown>;
            }) => {
                const projects = dbState.projects.filter((project) => {
                    if (!where) {
                        return true;
                    }
                    return Object.entries(where).every(([key, value]) => {
                        if (key === "deletedAt") {
                            return ((project as any).deletedAt ?? null) === value;
                        }
                        if (key === "NOT") {
                            return true;
                        }
                        return (project as any)[key] === value;
                    });
                });
                return projects[0] ?? null;
            }),
            findUnique: vi.fn(async ({ where }: {
                where: {
                    id: string;
                };
            }) => {
                return dbState.projects.find((p) => p.id === where.id) ?? null;
            }),
            findMany: vi.fn(async () => {
                return [...dbState.projects];
            }),
            count: vi.fn(async () => dbState.projects.length),
            update: vi.fn(async ({ where, data }: {
                where: {
                    id: string;
                };
                data: Record<string, unknown>;
            }) => {
                const p = dbState.projects.find((x) => x.id === where.id);
                if (!p) {
                    throw new Error("Project not found");
                }
                Object.assign(p, data);
                return { ...p };
            })
        },
        deployment: {
            findFirst: vi.fn(async () => null),
            create: vi.fn(async ({ data }: {
                data: Record<string, unknown>;
            }) => {
                const id = randomUUID();
                const row = {
                    id,
                    createdAt: new Date(),
                    ...data
                };
                dbState.deployments.push(row);
                return row;
            }),
            update: vi.fn(async ({ where, data }: {
                where: {
                    id: string;
                };
                data: Record<string, unknown>;
            }) => {
                const row = dbState.deployments.find((d) => d.id === where.id);
                if (!row) {
                    throw new Error("Deployment not found");
                }
                Object.assign(row, data);
                return { ...row };
            }),
            findUnique: vi.fn(async ({ where, include }: {
                where: {
                    id: string;
                };
                include?: {
                    project?: boolean;
                };
            }) => {
                const row = dbState.deployments.find((d) => d.id === where.id);
                if (!row) {
                    return null;
                }
                if (include?.project) {
                    const project = dbState.projects.find((p) => p.id === row.projectId);
                    return { ...row, project };
                }
                return { ...row };
            }),
            findMany: vi.fn(async () => {
                return [...dbState.deployments];
            })
        },
        containerImage: {
            create: vi.fn(async ({ data }: {
                data: Record<string, unknown>;
            }) => ({
                id: randomUUID(),
                createdAt: new Date(),
                ...data
            }))
        }
    };
}
