const axios = require('axios');

const BASE = process.env.BASE_URL || 'http://localhost:4000';

async function run() {
  try {
    console.log('Registering user...');
    const reg = await axios.post(`${BASE}/api/auth/register`, { email: 'dev@example.com', password: 'Password123!', fullName: 'Dev User' }, { headers: { 'Content-Type': 'application/json' } });
    console.log('Register response:', reg.status, reg.data);
  } catch (err) {
    if (err.response) console.log('Register failed:', err.response.status, err.response.data);
    else console.error('Register error:', err.message);
  }

  try {
    console.log('Logging in...');
    const login = await axios.post(`${BASE}/api/auth/login`, { email: 'dev@example.com', password: 'Password123!' }, { headers: { 'Content-Type': 'application/json' } });
    console.log('Login response:', login.status, Object.keys(login.data));
    const token = login.data.token;

    if (!token) {
      console.error('No token returned, aborting further tests.');
      process.exit(1);
    }

    console.log('Creating project...');
    const project = await axios.post(`${BASE}/api/project`, { projectName: 'demo-project', gitRepositoryUrl: 'https://example.com/repo.git', branch: 'main', language: 'spring-boot', autoGenerateDockerfile: false, autoGenerateHelmChart: false }, { headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' } });
    console.log('Create project status:', project.status, project.data.id);

    console.log('Listing projects...');
    const list = await axios.get(`${BASE}/api/project`, { headers: { Authorization: `Bearer ${token}` } });
    console.log('Projects count:', Array.isArray(list.data) ? list.data.length : 'unexpected');

    const projectId = (project.data && project.data.id) || (list.data && list.data[0] && list.data[0].id);
    if (!projectId) {
      console.error('No projectId found, stopping.');
      process.exit(1);
    }

    console.log('Trigger build...');
    const build = await axios.post(`${BASE}/api/build/${projectId}`, {}, { headers: { Authorization: `Bearer ${token}` } });
    console.log('Build:', build.status, build.data);

    console.log('Trigger deploy...');
    const deploy = await axios.post(`${BASE}/api/deploy/${projectId}`, {}, { headers: { Authorization: `Bearer ${token}` } });
    console.log('Deploy:', deploy.status, deploy.data);

    console.log('Security:', (await axios.get(`${BASE}/api/security/${projectId}`, { headers: { Authorization: `Bearer ${token}` } })).data);
    console.log('Metrics:', (await axios.get(`${BASE}/api/metrics/${projectId}`, { headers: { Authorization: `Bearer ${token}` } })).data);

    console.log('Smoke tests completed.');
    process.exit(0);
  } catch (err) {
    console.error('Smoke test error:', err && err.message ? err.message : err);
    process.exit(1);
  }
}

run();
