import { z } from "zod";
import { Prisma } from "@prisma/client";
import { resolveBuildPlan } from "@/server/build-planner";
import { resolveAppUrlForClient } from "@/server/deploy/app-public-url";
import { prisma } from "@/server/db/prisma";
import { ForbiddenError, NotFoundError, ValidationError } from "@/server/http/errors";
import { detectRepositoryLanguage } from "@/server/projects/repository-language";
import { ensureArgoCdApplication } from "@/server/services/argocd-service";
import type { PendingGitHubPush, Project, ProjectRequest, UserRole } from "@/types";
const createProjectSchema = z.object({
    projectName: z.string().min(2).max(120),
    gitRepositoryUrl: z.string().url(),
    branch: z.string().min(1).max(120),
    gitCredentialsId: z.string().trim().max(200).optional().default(""),
    language: z.string().trim().max(100).optional().default(""),
    buildProfile: z.enum(["node", "python", "java", "static", "custom"]).optional(),
    autoGenerateDockerfile: z.boolean().default(false),
    autoGenerateHelmChart: z.boolean().default(false)
});
const updateProjectSchema = z.object({
    projectName: z.string().min(2).max(120).optional(),
    gitRepositoryUrl: z.string().url().optional(),
    branch: z.string().min(1).max(120).optional(),
    gitCredentialsId: z.string().trim().max(200).optional(),
    language: z.string().min(2).max(100).optional(),
    buildProfile: z.enum(["node", "python", "java", "static", "custom"]).optional(),
    autoGenerateDockerfile: z.boolean().optional(),
    autoGenerateHelmChart: z.boolean().optional()
});
function toNamespace(projectName: string): string {
    return projectName
        .toLowerCase()
        .replace(/[^a-z0-9-]/g, "-")
        .replace(/-+/g, "-")
        .replace(/^-|-$/g, "");
}
function activeProjectWhere(extra: Prisma.ProjectWhereInput = {}): Prisma.ProjectWhereInput {
    return { deletedAt: null, ...extra };
}
function normalizePendingGitHubPush(raw: unknown): PendingGitHubPush | null {
    if (raw == null || typeof raw !== "object") {
        return null;
    }
    const o = raw as Record<string, unknown>;
    const branch = typeof o.branch === "string" ? o.branch : "";
    const after = typeof o.after === "string" ? o.after : "";
    const cloneUrl = typeof o.cloneUrl === "string" ? o.cloneUrl : "";
    const fullName = typeof o.fullName === "string" ? o.fullName : "";
    const receivedAt = typeof o.receivedAt === "string" ? o.receivedAt : "";
    if (!branch && !after && !cloneUrl) {
        return null;
    }
    return { branch, after, cloneUrl, fullName, receivedAt };
}
function mapProject(project: {
    id: string;
    projectName: string;
    gitRepositoryUrl: string;
    branch: string;
    gitCredentialsId: string | null;
    language: string;
    namespace: string;
    imageTag: string | null;
    buildStatus: string;
    lastDeploymentStatus: string;
    podStatus: string;
    createdAt: Date;
    autoGenerateDockerfile: boolean;
    autoGenerateHelmChart: boolean;
    url: string | null;
    pendingGitHubPush?: unknown | null;
}): Project {
    const buildPlan = resolveBuildPlan(project);
    return {
        id: project.id,
        projectName: project.projectName,
        gitRepositoryUrl: project.gitRepositoryUrl,
        branch: project.branch,
        gitCredentialsId: project.gitCredentialsId ?? "",
        language: project.language,
        buildProvider: buildPlan.provider,
        buildProfile: buildPlan.profile,
        buildMode: buildPlan.mode,
        buildTemplateName: buildPlan.templateName,
        buildTemplateVersion: buildPlan.templateVersion,
        buildDetectionReason: buildPlan.detectionReason,
        namespace: project.namespace,
        imageTag: project.imageTag ?? "",
        buildStatus: project.buildStatus,
        lastDeploymentStatus: project.lastDeploymentStatus,
        podStatus: project.podStatus,
        createdAt: project.createdAt.toISOString(),
        autoGenerateDockerfile: project.autoGenerateDockerfile,
        autoGenerateHelmChart: project.autoGenerateHelmChart,
        url: resolveAppUrlForClient(project.projectName, project.url),
        pendingGitHubPush: normalizePendingGitHubPush(project.pendingGitHubPush)
    };
}
export async function createProject(payload: unknown, userId: string): Promise<Project> {
    const parsed = createProjectSchema.safeParse(payload);
    if (!parsed.success) {
        throw new ValidationError(parsed.error.flatten().formErrors.join(", ") || "Invalid project payload");
    }
    const existing = await prisma.project.findFirst({
        where: activeProjectWhere({ projectName: parsed.data.projectName })
    });
    if (existing) {
        throw new ValidationError("Project name already exists");
    }
    const detected = await detectRepositoryLanguage({
        gitRepositoryUrl: parsed.data.gitRepositoryUrl,
        branch: parsed.data.branch
    });
    const resolvedLanguage = parsed.data.language.trim() || detected.language;
    const namespace = toNamespace(parsed.data.projectName);
    const created = await prisma.project.create({
        data: {
            projectName: parsed.data.projectName,
            gitRepositoryUrl: parsed.data.gitRepositoryUrl,
            branch: parsed.data.branch,
            gitCredentialsId: parsed.data.gitCredentialsId.trim() || null,
            language: parsed.data.buildProfile ?? resolvedLanguage,
            autoGenerateDockerfile: parsed.data.autoGenerateDockerfile,
            autoGenerateHelmChart: parsed.data.autoGenerateHelmChart,
            namespace,
            createdById: userId
        }
    });
    try {
        await ensureArgoCdApplication(parsed.data.projectName, namespace);
    }
    catch {
    }
    return mapProject(created);
}
export async function listProjects(userId: string, role: "ADMIN" | "DEVELOPER"): Promise<Project[]> {
    const projects = await prisma.project.findMany({
        where: activeProjectWhere(role === "ADMIN" ? {} : { createdById: userId }),
        orderBy: { createdAt: "desc" }
    });
    return projects.map(mapProject);
}
export async function getProjectById(projectId: string) {
    const project = await prisma.project.findFirst({
        where: activeProjectWhere({ id: projectId })
    });
    if (!project) {
        throw new NotFoundError("Project not found");
    }
    return project;
}
export async function assertProjectAccess(projectId: string, userId: string, role: UserRole, options?: {
    includeDeleted?: boolean;
}) {
    const project = await prisma.project.findFirst({
        where: options?.includeDeleted ? { id: projectId } : activeProjectWhere({ id: projectId })
    });
    if (!project) {
        throw new NotFoundError("Project not found");
    }
    if (role !== "ADMIN" && project.createdById !== userId) {
        throw new ForbiddenError("You do not have access to this project");
    }
    return project;
}
export async function getProjectForUser(projectId: string, userId: string, role: UserRole): Promise<Project> {
    const project = await assertProjectAccess(projectId, userId, role);
    return mapProject(project);
}
export async function updateProjectForUser(projectId: string, payload: unknown, userId: string, role: UserRole): Promise<Project> {
    await assertProjectAccess(projectId, userId, role);
    const parsed = updateProjectSchema.safeParse(payload);
    if (!parsed.success) {
        throw new ValidationError(parsed.error.flatten().formErrors.join(", ") || "Invalid update payload");
    }
    const data = parsed.data;
    if (data.projectName) {
        const taken = await prisma.project.findFirst({
            where: activeProjectWhere({ projectName: data.projectName, NOT: { id: projectId } })
        });
        if (taken) {
            throw new ValidationError("Project name already exists");
        }
    }
    const sanitized = Object.fromEntries(Object.entries(data).filter(([, value]) => value !== undefined)) as z.infer<typeof updateProjectSchema>;
    const { buildProfile, ...rest } = sanitized;
    const updated = await prisma.project.update({
        where: { id: projectId },
        data: {
            ...rest,
            ...(typeof rest.gitCredentialsId === "string" ? { gitCredentialsId: rest.gitCredentialsId.trim() || null } : {}),
            ...(buildProfile ? { language: buildProfile } : {}),
            ...(rest.projectName ? { namespace: toNamespace(rest.projectName) } : {})
        }
    });
    return mapProject(updated);
}
export async function deleteProjectForUser(projectId: string, userId: string, role: UserRole) {
    await assertProjectAccess(projectId, userId, role);
    await prisma.project.update({
        where: { id: projectId },
        data: { deletedAt: new Date() }
    });
}
export async function updateProject(projectId: string, data: Prisma.ProjectUpdateInput) {
    return prisma.project.update({ where: { id: projectId }, data });
}
export async function clearPendingGitHubPush(projectId: string): Promise<void> {
    await prisma.project.update({
        where: { id: projectId },
        data: { pendingGitHubPush: Prisma.DbNull }
    });
}
export async function countProjects() {
    const total = await prisma.project.count({ where: { deletedAt: null } });
    const running = await prisma.project.count({
        where: { deletedAt: null, lastDeploymentStatus: "SUCCESS" }
    });
    const failedBuilds = await prisma.project.count({ where: { deletedAt: null, buildStatus: "FAILED" } });
    return { total, running, failedBuilds };
}
export function mapProjectToResponse(project: {
    id: string;
    namespace: string;
    imageTag: string | null;
    podStatus: string;
    buildLogs: string | null;
    deploymentLogs: string | null;
    language: string;
    gitRepositoryUrl?: string | null;
    autoGenerateDockerfile?: boolean;
    lastDeploymentStatus: string;
}) {
    const buildPlan = resolveBuildPlan(project);
    return {
        projectId: project.id,
        namespace: project.namespace,
        imageTag: project.imageTag ?? "",
        podStatus: project.podStatus,
        buildLogs: project.buildLogs ?? "",
        deploymentLogs: project.deploymentLogs ?? "",
        buildProvider: buildPlan.provider,
        buildProfile: buildPlan.profile,
        buildMode: buildPlan.mode,
        lastDeploymentStatus: project.lastDeploymentStatus
    };
}
export type CreateProjectPayload = ProjectRequest;
