import { z } from "zod";
import { prisma } from "@/server/db/prisma";
import { ForbiddenError, NotFoundError, ValidationError } from "@/server/http/errors";
import type { Project, ProjectRequest, UserRole } from "@/types";

const createProjectSchema = z.object({
  projectName: z.string().min(2).max(120),
  gitRepositoryUrl: z.string().url(),
  branch: z.string().min(1).max(120),
  language: z.string().min(2).max(100),
  autoGenerateDockerfile: z.boolean().default(false),
  autoGenerateHelmChart: z.boolean().default(false)
});

const updateProjectSchema = z.object({
  projectName: z.string().min(2).max(120).optional(),
  gitRepositoryUrl: z.string().url().optional(),
  branch: z.string().min(1).max(120).optional(),
  language: z.string().min(2).max(100).optional(),
  autoGenerateDockerfile: z.boolean().optional(),
  autoGenerateHelmChart: z.boolean().optional()
});

function toNamespace(projectName: string): string {
  return projectName
    .toLowerCase()
    .replace(/[^a-z0-9-]/g, "-")
    .replace(/-+/g, "-")
    .replace(/^-|-$/g, "");
}

function mapProject(project: {
  id: string;
  projectName: string;
  gitRepositoryUrl: string;
  branch: string;
  language: string;
  namespace: string;
  imageTag: string | null;
  buildStatus: string;
  lastDeploymentStatus: string;
  podStatus: string;
  createdAt: Date;
  autoGenerateDockerfile: boolean;
  autoGenerateHelmChart: boolean;
  url: string | null;
}): Project {
  return {
    id: project.id,
    projectName: project.projectName,
    gitRepositoryUrl: project.gitRepositoryUrl,
    branch: project.branch,
    language: project.language,
    namespace: project.namespace,
    imageTag: project.imageTag ?? "",
    buildStatus: project.buildStatus,
    lastDeploymentStatus: project.lastDeploymentStatus,
    podStatus: project.podStatus,
    createdAt: project.createdAt.toISOString(),
    autoGenerateDockerfile: project.autoGenerateDockerfile,
    autoGenerateHelmChart: project.autoGenerateHelmChart,
    url: project.url ?? ""
  };
}

export async function createProject(payload: unknown, userId: string): Promise<Project> {
  const parsed = createProjectSchema.safeParse(payload);
  if (!parsed.success) {
    throw new ValidationError(parsed.error.flatten().formErrors.join(", ") || "Invalid project payload");
  }

  const existing = await prisma.project.findUnique({ where: { projectName: parsed.data.projectName } });
  if (existing) {
    throw new ValidationError("Project name already exists");
  }

  const created = await prisma.project.create({
    data: {
      projectName: parsed.data.projectName,
      gitRepositoryUrl: parsed.data.gitRepositoryUrl,
      branch: parsed.data.branch,
      language: parsed.data.language,
      autoGenerateDockerfile: parsed.data.autoGenerateDockerfile,
      autoGenerateHelmChart: parsed.data.autoGenerateHelmChart,
      namespace: toNamespace(parsed.data.projectName),
      createdById: userId
    }
  });

  return mapProject(created);
}

export async function listProjects(userId: string, role: "ADMIN" | "DEVELOPER"): Promise<Project[]> {
  const projects = await prisma.project.findMany({
    where: role === "ADMIN" ? {} : { createdById: userId },
    orderBy: { createdAt: "desc" }
  });

  return projects.map(mapProject);
}

export async function getProjectById(projectId: string) {
  const project = await prisma.project.findUnique({ where: { id: projectId } });
  if (!project) {
    throw new NotFoundError("Project not found");
  }
  return project;
}

export async function assertProjectAccess(projectId: string, userId: string, role: UserRole) {
  const project = await prisma.project.findUnique({ where: { id: projectId } });
  if (!project) {
    throw new NotFoundError("Project not found");
  }
  if (role !== "ADMIN" && project.createdById !== userId) {
    throw new ForbiddenError("You do not have access to this project");
  }
  return project;
}

export async function getProjectForUser(projectId: string, userId: string, role: UserRole): Promise<Project> {
  const project = await assertProjectAccess(projectId, userId, role);
  return mapProject(project);
}

export async function updateProjectForUser(
  projectId: string,
  payload: unknown,
  userId: string,
  role: UserRole
): Promise<Project> {
  await assertProjectAccess(projectId, userId, role);
  const parsed = updateProjectSchema.safeParse(payload);
  if (!parsed.success) {
    throw new ValidationError(parsed.error.flatten().formErrors.join(", ") || "Invalid update payload");
  }

  const data = parsed.data;
  if (data.projectName) {
    const taken = await prisma.project.findFirst({
      where: { projectName: data.projectName, NOT: { id: projectId } }
    });
    if (taken) {
      throw new ValidationError("Project name already exists");
    }
  }

  const sanitized = Object.fromEntries(
    Object.entries(data).filter(([, value]) => value !== undefined)
  ) as z.infer<typeof updateProjectSchema>;

  const updated = await prisma.project.update({
    where: { id: projectId },
    data: {
      ...sanitized,
      ...(sanitized.projectName ? { namespace: toNamespace(sanitized.projectName) } : {})
    }
  });

  return mapProject(updated);
}

export async function deleteProjectForUser(projectId: string, userId: string, role: UserRole) {
  await assertProjectAccess(projectId, userId, role);
  await prisma.project.delete({ where: { id: projectId } });
}

export async function updateProject(projectId: string, data: Record<string, unknown>) {
  return prisma.project.update({ where: { id: projectId }, data });
}

export async function countProjects() {
  const total = await prisma.project.count();
  const running = await prisma.project.count({ where: { lastDeploymentStatus: "SUCCESS" } });
  const failedBuilds = await prisma.project.count({ where: { buildStatus: "FAILED" } });

  return { total, running, failedBuilds };
}

export function mapProjectToResponse(project: {
  id: string;
  namespace: string;
  imageTag: string | null;
  podStatus: string;
  buildLogs: string | null;
  deploymentLogs: string | null;
  lastDeploymentStatus: string;
}) {
  return {
    projectId: project.id,
    namespace: project.namespace,
    imageTag: project.imageTag ?? "",
    podStatus: project.podStatus,
    buildLogs: project.buildLogs ?? "",
    deploymentLogs: project.deploymentLogs ?? "",
    lastDeploymentStatus: project.lastDeploymentStatus
  };
}

export type CreateProjectPayload = ProjectRequest;
