apiVersion: v1
kind: Secret
metadata:
  name: paas-build-registry
  namespace: tekton-pipelines
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: <base64-docker-config-json>
---
apiVersion: v1
kind: Secret
metadata:
  name: paas-build-git
  namespace: tekton-pipelines
type: kubernetes.io/basic-auth
stringData:
  username: git-user
  password: git-token
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: paas-build-bot
  namespace: tekton-pipelines
secrets:
  - name: paas-build-registry
  - name: paas-build-git
