import { DeploymentFailureReason, DeploymentJobStatus } from "@prisma/client";
import { DEPLOYMENT_LOG_TAIL_MAX_CHARS } from "@/server/constants/deploy";
import { resolveBuildPlan } from "@/server/build-planner";
import { env } from "@/server/config/env";
import { prisma } from "@/server/db/prisma";
import { buildMetadataLines, formatArtifactReference } from "@/server/build-metadata";
import { buildAppPublicUrl } from "@/server/deploy/app-public-url";
import { probeAppUrlReachability } from "@/server/deploy/deploy-reachability";
import { buildDeployImageRepository } from "@/server/deploy/deploy-image";
import { commitHelmValuesGitHub } from "@/server/gitops/gitops-github-service";
import { updateProject } from "@/server/projects/project-service";
import { getSecurityMetrics } from "@/server/security/security-service";
import { waitForArgoApplicationReady, syncArgoApplication } from "@/server/services/argocd-service";
import { clearDeploymentFailureFields, recordDeploymentFailure } from "@/server/services/deployment-failure";
import { ensureProjectNamespaceReady } from "@/server/services/namespace-setup-service";

function tail(s: string): string {
    return s.length <= DEPLOYMENT_LOG_TAIL_MAX_CHARS ? s : s.slice(-DEPLOYMENT_LOG_TAIL_MAX_CHARS);
}

interface PromoteDeploymentInput {
    provider: "jenkins" | "tekton";
    runId: string;
    runNumber: number | null;
    artifactImage: string | null;
    artifactDigest: string | null;
    buildLogTail: string;
}

async function persistFailure(deploymentId: string, projectId: string, fullLog: string, reason: DeploymentFailureReason, shortMessage: string): Promise<void> {
    const logs = tail(fullLog);
    await recordDeploymentFailure(deploymentId, projectId, {
        reason,
        message: shortMessage,
        logs
    });
}

export async function promoteDeploymentAfterJenkinsSuccess(deploymentId: string, projectId: string, projectName: string, jenkinsBuildNumber: number, jenkinsLogTail: string): Promise<void> {
    await promoteDeploymentAfterBuildSuccess(deploymentId, projectId, projectName, {
        provider: "jenkins",
        runId: String(jenkinsBuildNumber),
        runNumber: jenkinsBuildNumber,
        artifactImage: `${buildDeployImageRepository(projectName)}:${jenkinsBuildNumber}`,
        artifactDigest: null,
        buildLogTail: jenkinsLogTail
    });
}

export async function promoteDeploymentAfterBuildSuccess(deploymentId: string, projectId: string, projectName: string, input: PromoteDeploymentInput): Promise<void> {
    let imageRef = input.artifactImage;
    if (!imageRef) {
        try {
            imageRef =
                input.runNumber === null
                    ? null
                    : `${buildDeployImageRepository(projectName)}:${input.runNumber}`;
        }
        catch (error) {
            const msg = error instanceof Error ? error.message : String(error);
            await persistFailure(deploymentId, projectId, `${input.buildLogTail}\n\n[deploy] Could not build image reference: ${msg}`, DeploymentFailureReason.IMAGE_REF, msg);
            return;
        }
    }
    if (!imageRef) {
        await persistFailure(deploymentId, projectId, `${input.buildLogTail}\n\n[deploy] Build backend completed without an artifact image.`, DeploymentFailureReason.IMAGE_REF, "Build backend completed without an artifact image.");
        return;
    }
    const projectRow = await prisma.project.findUnique({
        where: { id: projectId },
        select: {
            namespace: true,
            language: true,
            gitRepositoryUrl: true,
            autoGenerateDockerfile: true
        }
    });
    const buildPlan = resolveBuildPlan(projectRow ?? { language: "custom" });
    const artifactRef = formatArtifactReference(imageRef, input.artifactDigest) ?? imageRef;
    const buildSection = [
        ...buildMetadataLines({
            provider: input.provider,
            profile: buildPlan.profile,
            mode: buildPlan.mode,
            templateName: buildPlan.templateName,
            templateVersion: buildPlan.templateVersion,
            detectionReason: buildPlan.detectionReason,
            zeroConfig: buildPlan.zeroConfig
        }, {
            runId: input.runId,
            runNumber: input.runNumber,
            artifactImage: imageRef,
            artifactDigest: input.artifactDigest
        }),
        tail(input.buildLogTail)
    ]
        .filter(Boolean)
        .join("\n");
    const buildPart = tail(buildSection);
    const sections: string[] = [
        buildPart,
        "",
        "--- GitOps (Helm values) + Argo CD ---",
        `[image] ${artifactRef}`,
        `[build-profile] ${buildPlan.profile}`
    ];
    await prisma.deployment.update({
        where: { id: deploymentId },
        data: { status: DeploymentJobStatus.SUCCESS, logs: buildPart, ...clearDeploymentFailureFields() }
    });
    await updateProject(projectId, {
        lastDeploymentStatus: "SUCCESS",
        deploymentLogs: buildPart,
        buildStatus: "PUSHING",
        imageTag: artifactRef
    });
    if (env.PAAS_ENFORCE_SECURITY_GATE === "true") {
        const security = await getSecurityMetrics(projectId);
        const enforcement = security.securityEnforcement;
        if (!enforcement?.deploymentAllowed) {
            const gateMsg = enforcement?.summary || "Security gate did not pass.";
            sections.push(`[security-gate] BLOCKED: ${gateMsg}`);
            sections.push(`PAAS_DEPLOY_VERIFY step=security_gate status=FAIL detail=${gateMsg.slice(0, 400)}`);
            await persistFailure(deploymentId, projectId, sections.join("\n"), DeploymentFailureReason.UNKNOWN, gateMsg);
            return;
        }
        sections.push(`PAAS_DEPLOY_VERIFY step=security_gate status=OK detail=${(enforcement.summary || "Security gate passed.").slice(0, 300)}`);
    }
    await prisma.deployment.update({
        where: { id: deploymentId },
        data: { status: DeploymentJobStatus.DEPLOYING, ...clearDeploymentFailureFields() }
    });
    await updateProject(projectId, { lastDeploymentStatus: "PROMOTING" });
    await prisma.containerImage.create({
        data: {
            projectId,
            imageRef,
            registry: "harbor",
            action: "PROMOTE",
            digest: input.artifactDigest ?? null,
            logs: buildPart
        }
    }).catch(() => null);
    const destNamespace = projectRow?.namespace?.trim() || projectName.toLowerCase().replace(/[^a-z0-9-]/g, "-");
    const namespacePrep = await ensureProjectNamespaceReady(destNamespace);
    if (namespacePrep.logs) {
        sections.push(namespacePrep.logs);
    }
    for (const warning of namespacePrep.warnings) {
        sections.push(`[k8s] WARN: ${warning}`);
    }
    try {
        const git = await commitHelmValuesGitHub(projectName, artifactRef, { buildProfile: buildPlan.profile });
        sections.push(`[gitops] committed ${git.ref}`);
        const bootstrapNote = git.chartBootstrapped ? " chart_bootstrapped=apps/simple-app" : "";
        sections.push(`PAAS_DEPLOY_VERIFY step=gitops status=OK detail=committed ${git.ref}${bootstrapNote}`);
    }
    catch (e) {
        const msg = e instanceof Error ? e.message : String(e);
        sections.push(`[gitops] FAILED: ${msg}`);
        sections.push(`PAAS_DEPLOY_VERIFY step=gitops status=FAIL detail=${msg.slice(0, 400)}`);
        await persistFailure(deploymentId, projectId, sections.join("\n"), DeploymentFailureReason.GITOPS, msg);
        return;
    }
    sections.push(`[build-meta] paas_strict_integrations=${env.PAAS_STRICT_INTEGRATIONS}`);
    let argoSyncOk = false;
    try {
        const argo = await syncArgoApplication(projectName, destNamespace);
        sections.push(argo.logs);
        if (/Sync accepted|already exists|created/i.test(argo.logs)) {
            sections.push(`PAAS_DEPLOY_VERIFY step=argocd_sync status=OK detail=${argo.logs.replace(/\s+/g, " ").slice(0, 300)}`);
            argoSyncOk = true;
        }
        else if (/WARN/i.test(argo.logs)) {
            sections.push(`PAAS_DEPLOY_VERIFY step=argocd_sync status=WARN detail=${argo.logs.replace(/\s+/g, " ").slice(0, 300)}`);
        }
    }
    catch (e) {
        const msg = e instanceof Error ? e.message : String(e);
        const lenientIntegrations = env.PAAS_STRICT_INTEGRATIONS !== "true";
        if (lenientIntegrations) {
            sections.push(`[argocd] WARN: ${msg} — continuing to wait for cluster (PAAS_STRICT_INTEGRATIONS=${env.PAAS_STRICT_INTEGRATIONS}).`);
            sections.push(`PAAS_DEPLOY_VERIFY step=argocd_sync status=WARN detail=${msg.slice(0, 400)}`);
        }
        else {
            sections.push(`[argocd] FAILED: ${msg}`);
            sections.push(`PAAS_DEPLOY_VERIFY step=argocd_sync status=FAIL detail=${msg.slice(0, 400)}`);
            await persistFailure(deploymentId, projectId, sections.join("\n"), DeploymentFailureReason.ARGOCD, msg);
            return;
        }
    }
    if (argoSyncOk || env.PAAS_STRICT_INTEGRATIONS !== "true") {
        const argoWait = await waitForArgoApplicationReady(projectName, { timeoutMs: env.PAAS_DEPLOY_WAIT_ARGO_MS });
        sections.push(argoWait.logs);
        if (argoWait.ready) {
            sections.push("PAAS_DEPLOY_VERIFY step=argocd_ready status=OK detail=Healthy+Synced");
        }
        else if (env.PAAS_STRICT_INTEGRATIONS === "true") {
            sections.push("PAAS_DEPLOY_VERIFY step=argocd_ready status=FAIL detail=timeout");
            await persistFailure(deploymentId, projectId, sections.join("\n"), DeploymentFailureReason.ARGOCD, "Argo CD application did not become Healthy and Synced in time.");
            return;
        }
        else {
            sections.push("PAAS_DEPLOY_VERIFY step=argocd_ready status=WARN detail=timeout");
        }
    }
    const appUrl = buildAppPublicUrl(projectName);
    const labIp = env.APPS_PUBLIC_LAB_NODE_IP.trim();
    let urlReachable = false;
    const postArgoDelayMs = Math.max(0, Number(process.env.PAAS_DEPLOY_POST_ARGO_PROBE_DELAY_MS ?? "15000") || 0);
    if (postArgoDelayMs > 0 && (argoSyncOk || env.PAAS_STRICT_INTEGRATIONS !== "true")) {
        sections.push(`[deploy] Waiting ${postArgoDelayMs}ms after Argo CD before HTTP probe…`);
        await new Promise((r) => setTimeout(r, postArgoDelayMs));
    }
    if (!labIp && !env.APPS_PUBLIC_URL_TEMPLATE.trim()) {
        sections.push(`PAAS_DEPLOY_VERIFY step=url status=WARN detail=${appUrl} — set APPS_PUBLIC_LAB_NODE_IP and APPS_PUBLIC_INGRESS_HTTP_PORT in PaaS env`);
    }
    else {
        const maxAttempts = Math.max(1, Math.floor(env.PAAS_DEPLOY_WAIT_HTTP_MS / env.PAAS_DEPLOY_HTTP_POLL_MS));
        const reachability = await probeAppUrlReachability(appUrl, {
            maxAttempts,
            delayMs: env.PAAS_DEPLOY_HTTP_POLL_MS,
            namespace: destNamespace,
            projectName
        });
        urlReachable = reachability.reachable;
        if (reachability.reachable) {
            const viaNote = reachability.via === "in_cluster"
                ? " (verified via in-cluster Service; public ingress may still propagate)"
                : "";
            sections.push(`PAAS_DEPLOY_VERIFY step=url status=OK detail=${appUrl} HTTP ${reachability.statusCode ?? "?"}${viaNote}`);
        }
        else {
            sections.push(`PAAS_DEPLOY_VERIFY step=url status=FAIL detail=${appUrl} (${reachability.error ?? "unreachable"})`);
        }
    }
    const probeConfigured = Boolean(labIp || env.APPS_PUBLIC_URL_TEMPLATE.trim());
    if (probeConfigured && !urlReachable) {
        const msg = `Application URL not reachable (${appUrl}). Check pod logs (kubectl logs), Argo CD sync, and Traefik ingress for ${projectName}.`;
        sections.push(`[deploy] FAILED: ${msg}`);
        await persistFailure(deploymentId, projectId, sections.join("\n"), DeploymentFailureReason.ARGOCD, msg);
        return;
    }
    const okLog = tail(sections.join("\n"));
    await prisma.deployment.update({
        where: { id: deploymentId },
        data: {
            status: DeploymentJobStatus.DEPLOYED,
            logs: okLog,
            url: appUrl,
            ...clearDeploymentFailureFields()
        }
    });
    await updateProject(projectId, {
        lastDeploymentStatus: "DEPLOYED",
        buildStatus: "READY",
        deploymentLogs: okLog,
        imageTag: artifactRef,
        url: appUrl
    });
}
