apiVersion: batch/v1
kind: Job
metadata:
  name: paas-prisma-push
  namespace: paas
  labels:
    app: paas-prisma-push
spec:
  ttlSecondsAfterFinished: 600
  backoffLimit: 3
  template:
    metadata:
      labels:
        app: paas-prisma-push
    spec:
      restartPolicy: OnFailure
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        fsGroup: 1001
      initContainers:
        - name: wait-postgres
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              until nc -z postgres.paas.svc.cluster.local 5432; do sleep 3; done
          securityContext:
            runAsNonRoot: true
            runAsUser: 1001
            allowPrivilegeEscalation: false
      containers:
        - name: prisma
          image: paas/frontend-db:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: paas-frontend-env
          securityContext:
            runAsNonRoot: true
            runAsUser: 1001
            allowPrivilegeEscalation: false
