#!/usr/bin/env python3
"""Render paas-deploy Jenkins load bundles (multi-file CPS split — avoids MethodTooLarge)."""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

BUNDLE_MARKER = "helm-portable-20260620-cps-split"
LEGACY_MARKER = "helm-portable-20260619"

# Output filenames under /var/jenkins_home/paas/
LOAD_FILES = (
    "paas-deploy-load-h1.groovy",
    "paas-deploy-load-h2.groovy",
    "paas-deploy-load-h3.groovy",
    "paas-deploy-stages.groovy",
)


def find_closure_end(lines: list[str], open_line: int) -> int:
    depth = 0
    started = False
    for i in range(open_line, len(lines)):
        for ch in lines[i]:
            if ch == "{":
                depth += 1
                started = True
            elif ch == "}":
                depth -= 1
        if started and depth == 0:
            return i
    raise ValueError(f"no matching closing brace at line {open_line + 1}")


def find_stage_line_indices(body_lines: list[str]) -> list[int]:
    indices: list[int] = []
    for i, line in enumerate(body_lines):
        if 'stage("Step ' in line and "—" in line:
            indices.append(i)
    if len(indices) != 12:
        raise ValueError(f"expected 12 stage() lines in runPaasDeploy body, found {len(indices)}")
    return indices


def split_helpers(lines: list[str], vars_start: int) -> tuple[str, str, str]:
    helper_lines = lines[:vars_start]
    # Split at def boundaries (keep uploadBom + early tooling in h1; crane push cluster in h2/h3).
    names = [i for i, ln in enumerate(helper_lines) if ln.startswith("def ")]
    if len(names) < 6:
        raise ValueError("too few helper defs to split")
    # h1: through ensureHelmTool; h2: through dockerlessNginx; h3: dockerlessImagePush + cosign snippet
    h1_end = next(i for i, ln in enumerate(helper_lines) if ln.startswith("def normalizeCosignPrivateKeyPem"))
    h2_end = next(i for i, ln in enumerate(helper_lines) if ln.startswith("def dockerlessImagePush("))
    return (
        "".join(helper_lines[:h1_end]),
        "".join(helper_lines[h1_end:h2_end]),
        "".join(helper_lines[h2_end:]),
    )


def split_stages_body(body_lines: list[str]) -> str:
    stage_idx = find_stage_line_indices(body_lines)
    chunks: list[tuple[str, int, int]] = []
    # env init before first stage
    if stage_idx[0] > 0:
        chunks.append(("runPaasDeployEnvInit", 0, stage_idx[0]))
    bounds = stage_idx + [len(body_lines)]
    groups = [
        ("runPaasDeploySteps1_2", 0, 2),
        ("runPaasDeployStep3", 2, 3),
        ("runPaasDeploySteps4_5", 3, 5),
        ("runPaasDeployStep6", 5, 6),
        ("runPaasDeploySteps7_8", 6, 8),
        ("runPaasDeploySteps9_12", 8, 12),
    ]
    out_parts: list[str] = []
    for name, g0, g1 in groups:
        if name == "runPaasDeployEnvInit":
            continue
        start = bounds[g0]
        end = bounds[g1]
        chunk = "".join(body_lines[start:end]).rstrip() + "\n"
        out_parts.append(f"def {name} = {{\n{chunk}}}\n")
    if stage_idx[0] > 0:
        init = "".join(body_lines[0 : stage_idx[0]]).rstrip() + "\n"
        out_parts.insert(0, f"def runPaasDeployEnvInit = {{\n{init}}}\n")
    calls = [
        "runPaasDeployEnvInit()",
        "runPaasDeploySteps1_2()",
        "runPaasDeployStep3()",
        "runPaasDeploySteps4_5()",
        "runPaasDeployStep6()",
        "runPaasDeploySteps7_8()",
        "runPaasDeploySteps9_12()",
    ]
    orchestrator = "def runPaasDeploy = {\n" + "\n".join(f"  {c}" for c in calls) + "\n}\n"
    return "".join(out_parts) + orchestrator


def header(part: str) -> str:
    return (
        f"// generated by render-loadable-stages.py ({part})\n"
        f"// dt-api-server-svc-20260617\n"
        f"// STAGES_BUNDLE_VERSION={BUNDLE_MARKER}\n"
    )


def render_bundle(main_path: Path) -> dict[str, str]:
    text = main_path.read_text(encoding="utf-8").replace("\r\n", "\n")
    lines = text.splitlines(keepends=True)
    vars_start = next(i for i, line in enumerate(lines) if line.startswith("def agentLabel = "))
    body_start = next(i for i, line in enumerate(lines) if line.startswith("def runPaasDeploy = {"))
    end = find_closure_end(lines, body_start)
    h1, h2, h3 = split_helpers(lines, vars_start)
    vars_block = "".join(lines[vars_start:body_start])
    body_lines = lines[body_start + 1 : end]
    stages_body = split_stages_body(body_lines)
    return {
        LOAD_FILES[0]: header("helpers h1") + h1,
        LOAD_FILES[1]: header("helpers h2") + h2,
        LOAD_FILES[2]: header("helpers h3") + h3,
        LOAD_FILES[3]: header("vars + stage closures") + vars_block + stages_body,
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--out-dir",
        type=Path,
        help="Write split bundle files to directory (default: stdout = stages file only for compat)",
    )
    parser.add_argument(
        "--stdout-stages-only",
        action="store_true",
        help="Emit only paas-deploy-stages.groovy on stdout (legacy)",
    )
    args = parser.parse_args()
    root = Path(__file__).resolve().parent
    main_path = root / "Jenkinsfile.paas-deploy"
    if not main_path.is_file():
        print(f"ERROR: missing {main_path}", file=sys.stderr)
        return 1
    split_script = root / "split-cps-hotspots.py"
    if split_script.is_file():
        import subprocess

        subprocess.run([sys.executable, str(split_script)], check=False)
    try:
        bundle = render_bundle(main_path)
    except (StopIteration, ValueError) as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1
    if args.out_dir:
        args.out_dir.mkdir(parents=True, exist_ok=True)
        for name, content in bundle.items():
            out = args.out_dir / name
            out.write_text(content, encoding="utf-8")
            print(f"OK wrote {out} ({len(content)} bytes)", file=sys.stderr)
        return 0
    if args.stdout_stages_only:
        sys.stdout.buffer.write(bundle[LOAD_FILES[3]].encode("utf-8"))
        return 0
    # Default: write all parts to stderr paths hint + stages on stdout for install script compat
    # Install script uses --out-dir; single-file stdout is the stages orchestrator file.
    sys.stdout.buffer.write(bundle[LOAD_FILES[3]].encode("utf-8"))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
