#!/usr/bin/env python3
from pathlib import Path
import sys


def main() -> int:
    root = Path(__file__).resolve().parent
    main_path = root / "Jenkinsfile.paas-deploy"
    if not main_path.is_file():
        print(f"ERROR: missing {main_path}", file=sys.stderr)
        return 1
    text = main_path.read_text(encoding="utf-8").replace("\r\n", "\n")
    lines = text.splitlines(keepends=True)

    try:
        vars_start = next(i for i, line in enumerate(lines) if line.startswith("def agentLabel = "))
        body_start = next(i for i, line in enumerate(lines) if line.startswith("def runPaasDeploy = {"))
    except StopIteration:
        print("ERROR: Jenkinsfile missing def agentLabel / def runPaasDeploy", file=sys.stderr)
        return 1

    helpers = "".join(lines[:vars_start])
    vars_block = "".join(lines[vars_start:body_start])
    # Keep the historical stages file as the source for stage body.
    stages_path = root / "Jenkinsfile.paas-deploy-stages.groovy"
    if not stages_path.is_file():
        print(f"ERROR: missing {stages_path}", file=sys.stderr)
        return 1
    stages_body = stages_path.read_text(encoding="utf-8").replace("\r\n", "\n").rstrip() + "\n"

    out = (
        "// generated by render-loadable-stages.py (helpers + vars + Steps 1-12 body)\n"
        + "// STAGES_BUNDLE_VERSION=dt-api-server-svc-20260617\n"
        + helpers
        + vars_block
        + stages_body
    )
    sys.stdout.buffer.write(out.encode("utf-8"))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
