#!/usr/bin/env python3
"""Emit Jenkins loadable stages: init + runPaasStep01..12 (Blue Ocean sees outer stages)."""
from __future__ import annotations

import re
import sys
from pathlib import Path

STAGE_RE = re.compile(r'^\s*stage\("Step (\d+) — (.+)"\) \{\s*$')
BUNDLE_MARKER = "STAGES_BUNDLE_VERSION=paas-blueocean-12steps-20260618"


def extract_step_body(lines: list[str], start_i: int, end_i: int) -> list[str]:
    """Stage body = inner lines + inter-stage tail; drop the stage() wrapper's closing `  }`."""
    chunk = lines[start_i + 1 : end_i]
    inner: list[str] = []
    tail: list[str] = []
    closed = False
    for line in chunk:
        if not closed and re.match(r"^  }\s*$", line):
            closed = True
            continue
        if closed:
            tail.append(line)
        else:
            inner.append(line)
    while tail and not tail[0].strip():
        tail.pop(0)
    while tail and not tail[-1].strip():
        tail.pop()
    return inner + tail


def split_stages_body(stages_text: str) -> tuple[list[str], list[tuple[int, str, list[str]]]]:
    lines = stages_text.splitlines()
    hits: list[tuple[int, int, str]] = []
    for i, line in enumerate(lines):
        m = STAGE_RE.match(line)
        if m:
            hits.append((i, int(m.group(1)), m.group(2)))
    if len(hits) < 12:
        raise SystemExit(f"ERROR: expected 12 stage() blocks, found {len(hits)}")
    init_lines = lines[: hits[0][0]]
    steps: list[tuple[int, str, list[str]]] = []
    for idx, (start_i, num, title) in enumerate(hits):
        end_i = hits[idx + 1][0] if idx + 1 < len(hits) else len(lines)
        body = extract_step_body(lines, start_i, end_i)
        steps.append((num, title, body))
    return init_lines, steps


def emit_function(name: str, body_lines: list[str]) -> str:
    if not body_lines:
        return f"def {name} = {{}}\n"
    body = "\n".join(body_lines)
    return f"def {name} = {{\n{body}\n}}\n"


def validate_step_body(num: int, title: str, body_lines: list[str]) -> None:
    body = "\n".join(body_lines)
    if re.search(r"\n  \}\n(\s*\n)?  [a-zA-Z\"']", body):
        raise SystemExit(
            f"ERROR: Step {num} ({title}) still has stage() wrapper brace before tail code"
        )


def main() -> int:
    root = Path(__file__).resolve().parent
    main_path = root / "Jenkinsfile.paas-deploy"
    stages_path = root / "Jenkinsfile.paas-deploy-stages.groovy"
    if not main_path.is_file():
        print(f"ERROR: missing {main_path}", file=sys.stderr)
        return 1
    if not stages_path.is_file():
        print(f"ERROR: missing {stages_path}", file=sys.stderr)
        return 1

    text = main_path.read_text(encoding="utf-8").replace("\r\n", "\n")
    lines = text.splitlines(keepends=True)
    try:
        vars_start = next(i for i, line in enumerate(lines) if line.startswith("def agentLabel = "))
        body_start = next(i for i, line in enumerate(lines) if line.startswith("def runPaasDeploy = {"))
    except StopIteration:
        print("ERROR: Jenkinsfile missing def agentLabel / def runPaasDeploy", file=sys.stderr)
        return 1

    helpers = "".join(lines[:vars_start])
    vars_block = "".join(lines[vars_start:body_start])
    stages_text = stages_path.read_text(encoding="utf-8").replace("\r\n", "\n")
    init_lines, steps = split_stages_body(stages_text)

    parts = [
        "// generated by render-loadable-stages.py (helpers + vars + init + runPaasStep01..12)\n",
        f"// {BUNDLE_MARKER}\n",
        helpers,
        vars_block,
        emit_function("paasDeployInit", init_lines),
    ]
    for num, title, body in steps:
        validate_step_body(num, title, body)
        parts.append(emit_function(f"runPaasStep{num:02d}", body))

    output = "".join(parts)
    sys.stdout.buffer.write(output.encode("utf-8"))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
