#!/usr/bin/env python3
"""Extract def runPaasDeploy = { ... } body into Jenkinsfile.paas-deploy-stages.groovy (June 17 monolith layout)."""
from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
MAIN = ROOT / "Jenkinsfile.paas-deploy"
STAGES = ROOT / "Jenkinsfile.paas-deploy-stages.groovy"
MARKER = "dt-api-server-svc-20260617-full"


def find_closure_end(lines: list[str], open_line: int) -> int:
    depth = 0
    started = False
    for i in range(open_line, len(lines)):
        for ch in lines[i]:
            if ch == "{":
                depth += 1
                started = True
            elif ch == "}":
                depth -= 1
        if started and depth == 0:
            return i
    raise ValueError(f"no closing brace for runPaasDeploy at line {open_line + 1}")


def main() -> int:
    if not MAIN.is_file():
        print(f"ERROR: missing {MAIN}", file=sys.stderr)
        return 1
    text = MAIN.read_text(encoding="utf-8").replace("\r\n", "\n")
    lines = text.splitlines(keepends=True)
    try:
        body_start = next(i for i, line in enumerate(lines) if line.startswith("def runPaasDeploy = {"))
    except StopIteration:
        print("ERROR: Jenkinsfile missing def runPaasDeploy = {", file=sys.stderr)
        return 1
    end = find_closure_end(lines, body_start)
    body = "".join(lines[body_start + 1 : end])
    if 'stage("Step 12 —' not in body:
        print("ERROR: runPaasDeploy body missing Step 12", file=sys.stderr)
        return 1
    header = (
        f"// STAGES_BODY_VERSION={MARKER}\n"
        "// generated by sync-stages-body-from-main.py — inline Steps 1-12 for June 17 monolith load\n"
    )
    STAGES.write_text(header + body, encoding="utf-8")
    print(f"OK: wrote {STAGES} ({len(body)} bytes, marker={MARKER})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
